### ISSUE TITLE
周期性的连接Apollo服务器端超时失败

### ISSUE THREAD

**Issue by jieqian** [zouyx/agollo#10]
在request.go中周期的性的发生连接Apollo config service的配置更新通知超时失败，大概每隔几分钟就发生一次，并超过最大重试次数后停止发生请求。比如
[ERROR] [19:49:07] [requestRecovery @ request.go.97] Connect Apollo Server Fail,Error:Get http://xxx.xxx.xxx.xxx:8080/notifications/v2?appId=xxx-xxx-xxx&cluster=default&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A448%7D%5D: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
[ERROR] [19:49:07] [requestRecovery @ request.go.97] Over Max Retry Still Error,Error:Get http://xxx.xxx.xxx.xxx:8080/notifications/v2?appId=xxx-xxx-xxx&cluster=default&notifications=%5B%7B%22namespaceName%22%3A

**Comment by zouyx** [comment]
@jieqian 你试试最新的版本（v1.0.2或者master）有没有问题，我把这个接口的超时时间调到了10分钟，和java客户端保持一致，之前是1s。

**Comment by eyotang** [comment]
[2020/02/22 21:09:04.522] [ERROR] [ucommon@v1.0.9/conf/agollo/log.go:54] [Connect Apollo Server Fail,Error: Get http://pro-uconf.xxx..com/services/config?appId=xxxxxxxxxxxxxxxxx&ip=xxx.xxx.xxx.xxx: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)]

**Comment by eyotang** [comment]
1.0.9还有这个问题

**Comment by zouyx** [comment]
@eyotang 十分感谢你的使用，是 curl 错误中的 url 是返回什么？我看了下错误提示，是因为没连接上你指定的域，或者连接的时候超时，请看下面的截图。

![image](https://user-images.githubusercontent.com/3828072/75131314-75287b00-570d-11ea-8e0c-fa5215f08099.png)

**Comment by eyotang** [comment]
@zouyx 后来抓包，定位了下。是我们IP这块使用了域名方式，Nginx上配置了长轮询超时时间为5min后，问题解决了。

**Comment by zouyx** [comment]
@eyotang 十分感谢你的反馈与分享。我觉得这个解决思路十分有用，值得记录。有什么问题随时和我联系。

**Comment by XieWeiXie** [comment]
朋友，这个问题，最终怎么解决？我这边 go 服务中使用了 apollo 配置中心。notification/v2 接口 504。上面看了一圈，貌似都在说这个长轮训的超时时间，所以这个时间，是 apollo 服务的某个启动配置之类的吗？不知道怎么解决，线上也看不到 apollo 对应的日志。
