### ISSUE TITLE
客户端容灾，连不上apollo时，没有使用本地的application.json文件配置信息

### ISSUE THREAD

**Issue by wang371758198** [zouyx/agollo#101]
在本地项目中有application.json文件，估计把app.properties文件中的ip地址写错，启动时
err := agollo.Start()
	if err != nil {
		fmt.Println(err)
	}

输入：notifySyncConfigServices: over Max Retry Still Error
但是没有使用上次本地存储的application.json文件的配置。通过agollo.GetStringValue("app_version", "")获取的配置信息还是空的。
麻烦问下容灾还需要其它配置吗？
使用的是github.com/zouyx/agollo/v3

**Comment by wang371758198** [comment]
`func syncConfigs(namespace string, isAsync bool) error {

	remoteConfigs, err := notifyRemoteConfig(nil, namespace, isAsync)

	if err != nil {
                //访问remoteConfigs，返回err时 直接return了，添加了loadBackupConfig，可以使用本地的缓存配置内容，进行容灾
		appConfig := env.GetPlainAppConfig()
		loadBackupConfig(appConfig.NamespaceName, appConfig)
		return fmt.Errorf("notifySyncConfigServices: %s", err)
	}
	if len(remoteConfigs) == 0 {
		return fmt.Errorf("notifySyncConfigServices: empty remote config")
	}

	updateAllNotifications(remoteConfigs)

	//sync all config
	err = AutoSyncConfigServices(nil)

	if err != nil {
		if namespace != "" {
			return nil
		}
		//first sync fail then load config file
		appConfig := env.GetPlainAppConfig()
		loadBackupConfig(appConfig.NamespaceName, appConfig)
	}

	//sync all config
	return nil
}`

**Comment by zouyx** [comment]
现在基本上是在同步失败后才执行客户端容灾，确实会有你说的问题，能麻烦你提交个 PR 吗？

**Comment by wang371758198** [comment]
PR提交了 [https://github.com/zouyx/agollo/pull/102](url)

**Comment by zouyx** [comment]
收到，麻烦你了

**Comment by wang371758198** [comment]
@zouyx 能否发布一个release 小版本？

**Comment by zouyx** [comment]
@wang371758198 可以

**Comment by zouyx** [comment]
v3.0.1，你看看要不要等构建完，构建完会自动 release

**Comment by wang371758198** [comment]
好的，那我close了
