### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sp56** [zouyx/agollo#103]
**请简单描述bug的场景**
agollo.Start() 的时候有概率出现如下错误，重试几次又会正常：

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x143ad75]

goroutine 7 [running]:
github.com/zouyx/agollo/v3.(*notificationsMap).getNotifies(0x0, 0x0, 0x0, 0x0, 0x0)
        xxxx/github.com/zouyx/agollo/v3@v3.0.0/componet_notify.go:45 +0x55
github.com/zouyx/agollo/v3.notifyRemoteConfig(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
       xxxx/github.com/zouyx/agollo/v3@v3.0.0/componet_notify.go:171 +0x6a
github.com/zouyx/agollo/v3.notifySyncConfigServices(0xc0001026f0, 0xc000220660)
        xxxx/github.com/zouyx/agollo/v3@v3.0.0/componet_notify.go:113 +0x36
created by github.com/zouyx/agollo/v3.startAgollo
       xxxx/github.com/zouyx/agollo/v3@v3.0.0/start.go:63 +0x51

**如何重现**

再现行为的步骤：

1.跳到“…”

2.点击“…”

3.向下滚动到“…”

4.见错误

**期望**
请描述期望发生什么

**截图**
如有

**Agollo 版本 :**

**日志信息**

**其他上下文**
如有

**Comment by zouyx** [comment]
@sp56 能不能提供一下你的重现场景，例如是：配置文件加载方式，就是用配置文件还是写程序，大概配置了什么 key。我看了下 v3.0.0/componet_notify.go:45 的这一行好像是空白行。

https://github.com/zouyx/agollo/blob/0c6a40fbff37779b7cb0b00814910a314df63111/component/notify/componet_notify.go#L45

getNotifies 这个方法是在 82 行之后

**Comment by sp56** [comment]
可能是start之后内部还没完全处理完，就开始getConfig调用。目前我在start的时候 sleep了两秒就没出现过了

**Comment by zouyx** [comment]
明白，我稍后看看
