### ISSUE TITLE
release v3.0.0 alpha的代码与仓库的代码不一致

### ISSUE THREAD

**Issue by hantmac** [zouyx/agollo#106]
https://github.com/zouyx/agollo/blob/92df33d92ba32e60e19b15ecc2e1f5f0a5db57cd/component/notify/componet_notify.go#L50

`go get -u github.com/zouyx/agollo/v3@v3.0.0-alpha`下载的包的代码`/componet/notify/componet_notify.go`中的代码是:
```
func init() {
	InitAllNotifications(nil)
}

//InitAllNotifications 初始化notificationsMap
func InitAllNotifications(callback func(namespace string)) {
	appConfig := env.GetPlainAppConfig()
	ns := env.SplitNamespaces(appConfig.NamespaceName, callback)
	allNotifications = &notificationsMap{
		notifications: ns,
	}
}
```

多了一个`init`函数，函数参数为`nil`，导致bug

**Comment by zouyx** [comment]
仓库的代码是 v3.0.1

**Comment by hantmac** [comment]
> 仓库的代码是 v3.0.1

所以是不是应该release稳定版？

**Comment by zouyx** [comment]
> > 仓库的代码是 v3.0.1
> 
> 所以是不是应该release稳定版？

![image](https://user-images.githubusercontent.com/3828072/78656107-7d252e80-78f9-11ea-84ca-e2c3f45abf4d.png)

我看首页是 release 是 v3.0.1 ，还有你说那个问题么，有的话我修复下。

**Comment by hantmac** [comment]
> > > 仓库的代码是 v3.0.1
> > 
> > 
> > 所以是不是应该release稳定版？
> 
> ![image](https://user-images.githubusercontent.com/3828072/78656107-7d252e80-78f9-11ea-84ca-e2c3f45abf4d.png)
> 
> 我看首页是 release 是 v3.0.1 ，还有你说那个问题么，有的话我修复下。

还是有问题，如果是使用app.properties文件不会触发这个bug,如果是使用自定义配置 config.appconfig就会走到空指针异常

**Comment by zouyx** [comment]
@hantmac 我看看

**Comment by zouyx** [comment]
我用 ```AGOLLO_CONF=config.appconfig``` 这个环境变量 v3.0.1 启动是没问题，你配置了吗？

**Comment by hantmac** [comment]
> 我用 `AGOLLO_CONF=config.appconfig` 这个环境变量 v3.0.1 启动是没问题，你配置了吗？代码在这里：https://github.com/zouyx/agollo_demo

我在代码和README里没找到配置这个环境变量的说明呀

**Comment by zouyx** [comment]
是的，我写在了 [wiki](https://github.com/zouyx/agollo/wiki/使用指南#1212环境变量指定配置文件)，你提了个非常好的问题。是否能麻烦一下，帮忙简单的优化下首页的 README.md？我也觉得这一块信息对用户是比较有用。

**Comment by hantmac** [comment]
我感觉用下来的体验就是，如果之前没用过Apollo，上手您这个lib感觉无所适从。我之前写过一点java但是没用过Apollo，工作后就一直写go,最近团队的一个项目要java转go，就找到了您这个项目。
感觉demo可以更完善一些，有时间我理一下README，到时候一起看一下。

**Comment by zouyx** [comment]
> 我感觉用下来的体验就是，如果之前没用过Apollo，上手您这个lib感觉无所适从。我之前写过一点java但是没用过Apollo，工作后就一直写go,最近团队的一个项目要java转go，就找到了您这个项目。
> 
> 感觉demo可以更完善一些，有时间我理一下README，到时候一起看一下。

十分感谢

**Comment by hantmac** [comment]
这个方式还是会报错：
```
readyConfig := &config.AppConfig{
		AppID:         "10494",
		Cluster:       "default",
		NamespaceName: "application",
		IP:            "x.x.x.x:8080",
	}
	agollo.InitCustomConfig(func() (*config.AppConfig, error) {
		return readyConfig, nil
	})
	err := agollo.Start()
```

**Comment by zouyx** [comment]
> 这个方式还是会报错：
> 
> ```
> readyConfig := &config.AppConfig{
> 		AppID:         "10494",
> 		Cluster:       "default",
> 		NamespaceName: "application",
> 		IP:            "x.x.x.x:8080",
> 	}
> 	agollo.InitCustomConfig(func() (*config.AppConfig, error) {
> 		return readyConfig, nil
> 	})
> 	err := agollo.Start()
> ```

是否能加一下我微信：yixianzou，我们再具体沟通一下？

**Comment by hantmac** [comment]
Solved.
