### ISSUE TITLE
[FEATURE]增加客户端鉴权

### ISSUE THREAD

**Issue by zouyx** [zouyx/agollo#108]
**功能适用的场景？**
该功能适用于xxx场景

**你需要的功能是否有关联问题？**
简明扼要地描述你需要的功能，当 [...]

**你期望的解决方案是？**
我期望改造xxx后，实现xxx

**Comment by codeMingo** [comment]
请问下这个开发好了吗？

**Comment by zouyx** [comment]
@codeMingo 没有，希望这个月能弄完。

**Comment by codeMingo** [comment]
Thanks，我们公司在调研，可能用你这个项目，发现没有鉴权

Joe Zou <notifications@github.com> 于2020年5月11日周一 上午11:46写道：

**Comment by zouyx** [comment]
鉴权是最近几个版本加的。所以，我也希望能跟上。

**Comment by ichiro999** [comment]
鉴权是指支持https拉取配置吗？

**Comment by zouyx** [comment]
不是，是支持 apollo 的鉴权功能。

**Comment by ichiro999** [comment]
有计划支持https拉取apollo的配置吗

**Comment by zouyx** [comment]
> 有计划支持https拉取apollo的配置吗

我有个问题，在内网应该是走 http 的吧？https 是因为走了外网么？我可以看看，如何支持。但我要找个环境模拟下。估计下周二左右给你个结果，你看可以不。

**Comment by zouyx** [comment]
@ichiro999 你可以搞个新的 issue 给我

**Comment by ichiro999** [comment]
我们这边要求必须走https，同时支持https关闭功能，可以

**Comment by guaosi** [comment]
请问何时增加客户端授权？

**Comment by zouyx** [comment]
@guaosi 我加了，得测试下

**Comment by guaosi** [comment]
@zouyx 只能支持json格式文件，不支持yml格式。这对于kubernets来说非常难受

**Comment by zouyx** [comment]
@guaosi 你说配置文件么？可以修改，给我点时间，兄弟。

**Comment by guaosi** [comment]
@zouyx 哈，我也只是提议一下。yml确实用的比json会多一点，token鉴权那个我自己也改了。目前就是发现parse解析只有json的。我现在要是改动太多，以后就不好跟着你的版本升级了

**Comment by zouyx** [comment]
@guaosi 没事，你也可以 pr 一下给我
