### ISSUE TITLE
agollo start后，main goroutin不能马上拿到config

### ISSUE THREAD

**Issue by jieqian** [zouyx/agollo#11]
如题

**Comment by zouyx** [comment]
@jieqian 我看了一下代码，你可以试试用agollo.Start()，不加go，应该可以达到你需要的效果。

**Comment by jieqian** [comment]
@zouyx 试过了， agollo.Start()后，直接getStringValue拿到的还是默认值

**Comment by jieqian** [comment]
@zouyx 如果同步启动agollo( agollo.Start() ),就可以马上拿到值了，👍

**Comment by zouyx** [comment]
@jieqian 谢谢你发现的bug
