### ISSUE TITLE
[FEATURE]LoggerInterface接口应该取消error的返回值

### ISSUE THREAD

**Issue by ichiro999** [zouyx/agollo#110]
**功能适用的场景？**

type LoggerInterface interface {
	Debugf(format string, params ...interface{})

	Infof(format string, params ...interface{})

	Warnf(format string, params ...interface{}) error

	Errorf(format string, params ...interface{}) error

	Debug(v ...interface{})

	Info(v ...interface{})

	Warn(v ...interface{}) error

	Error(v ...interface{}) error
}
日志接口定义里为什么要方法返回error，日志组件只是将apollo的客户端日志输出，不需要判断返回值

**你期望的解决方案是？**
建议直接去掉error的返回

**Comment by zouyx** [comment]
@ichiro999 如果改完可以提一下 PR

**Comment by ichiro999** [comment]
#111 已提交pr
