### ISSUE TITLE
[FEATURE]agollo支持yml格式的解析与写入

### ISSUE THREAD

**Issue by guaosi** [zouyx/agollo#114]
**功能适用的场景？**
该功能适用于不同配置文件格式的场景

**你需要的功能是否有关联问题？**
希望不仅仅只支持json，可以加入yml文件的读取与写入，Apollo服务端本身支持yml配置的下发

**你期望的解决方案是？**
希望可以实现支持Apollo服务端下发的yml文件的读取与写入

**Comment by rgshare** [comment]
我最近也遇到了相关问题，想的是添加listener，然后用viper去解析json、yml配置：
```go
func (h *eventHandler) OnChange(event *storage.ChangeEvent) {
	ns := event.Namespace
	format := strings.TrimLeft(filepath.Ext(ns), ".")
	vp := viper.New()

	// 默认类型
	if len(format) == 0 {
		format = "properties"
	}

	// 检测是否受viper支持
	if !stringInSlice(format, viper.SupportedExts) {
		logrus.Errorf("unsupported format, namespace: %s, config will be ignored.", ns)
		return
	}

	// 配置文件内容
	content := agollo.GetConfig(ns).GetContent(storage.Properties)
	buffer := bytes.NewBufferString(content)

	// 使用viper解析
	if err := vp.ReadConfig(buffer); err != nil {
		logrus.WithError(err).Errorf("parse config error, namespace: %s", ns)
	}

	// 保存结果
	apolloConfigs[ns] = vp
}
```
但事件触发是异步的，所以第一次可能获取不到配置信息，不知道有没有解决办法？

**Comment by zouyx** [comment]
> 我最近也遇到了相关问题，解决办法是通过添加listener，然后用viper去解析json、yml配置：
> 
> ```go
> // 初始化
> func init() {
>     if err := agollo.Start(); err != nil {
>         logrus.WithError(err).Errorf("load apollo config error")
>         panic(err)
>     }
> 
>     // 应用程序启动后，手动初始化所有namespace
>     appConfig := env.GetPlainAppConfig()
>     namespaces := env.SplitNamespaces(appConfig.NamespaceName, nil)
>     watcher := &eventWatcher{}
> 
>     namespaces.Range(func(key, value interface{}) bool {
>         watcher.parse(key.(string))
>         return true
>     })
> 
>     // 初始化完成后，监听事件
>     storage.AddChangeListener(watcher)
> }
> 
> var apolloConfigs = map[string]*viper.Viper{}
> 
> type eventWatcher struct {
> }
> 
> func (e *eventWatcher) OnChange(event *storage.ChangeEvent) {
>     e.parse(event.Namespace)
> }
> 
> func (e *eventWatcher) parse(namespace string) {
>     format := strings.TrimLeft(filepath.Ext(namespace), ".")
>     vp := viper.New()
> 
>     // 默认类型
>     if len(format) == 0 {
>         format = "properties"
>     }
> 
>     // 检测是否受viper支持
>     if !stringInSlice(format, viper.SupportedExts) {
>         logrus.Errorf("unsupported format, namespace: %s, config will be ignored.", namespace)
>         return
>     } else {
>         vp.SetConfigType(format)
>     }
> 
>     // 配置文件内容
>     content := agollo.GetConfig(namespace).GetContent(storage.ConfigFileFormat(format))
>     buffer := bytes.NewBufferString(content)
> 
>     // 使用viper解析
>     _ = vp.ReadConfig(buffer)
> 
>     // 保存结果
>     apolloConfigs[namespace] = vp
> }
> ```
> 
> 读取配置：
> 
> ```go
> // 测试
> func main() {
>     testNs := "application"
>     if vp, ok := apolloConfigs[testNs]; ok {
>         fmt.Println(vp.GetString("my.config"))
>     }
> }
> ```

大神，client 都要被玩坏了，没事，我马上搞。。。。
