### ISSUE TITLE
[BUG]yml配置解析错误

### ISSUE THREAD

**Issue by rgshare** [zouyx/agollo#118]
**请简单描述bug的场景**

当yml配置的格式是数组类型时，解析出来的结果是空。配置：
```yml
thrift:
  faiss:
    - xxx
    - xxx
```

原因是yml解析相关代码把配置统一当做`string`进行解析，而viper在做类型转换时，如果实际类型不是字符串返回的结果是空。

相关代码：
```go
func convertToMap(vp *viper.Viper) map[string]string {
	if vp == nil {
		return nil
	}

	m := make(map[string]string)
	for _, key := range vp.AllKeys() {
		m[key] = vp.GetString(key)
	}
	return m
}
```

**如何重现**
必现

**期望**
能够正确解析数组等格式。

**Agollo 版本 :**
 - Version 3.3.0

**Comment by rgshare** [comment]
或许需要修改的地方较多，我暂时还改不了。

**Comment by ichiro999** [comment]
@zouyx 这个问题根本原因是paser接口为什么要定义成map[string]string返回，应该使用map[string]interface{}，并且提供slice配置的返回类型，这样就可以

**Comment by zouyx** [comment]
@rgshare 我先修复一下问题，稍后我会重构一下存储。

**Comment by guaosi** [comment]
我感觉不对啊，我配置中心是yml格式，同步到客户端也应该是yml格式吧，现在还是json格式，这样没什么用处吧，无非就是改一个后缀，我本地需要的是yml格式的内容啊 @zouyx

**Comment by zouyx** [comment]
> 我感觉不对啊，我配置中心是yml格式，同步到客户端也应该是yml格式吧，现在还是json格式，这样没什么用处吧，无非就是改一个后缀，我本地需要的是yml格式的内容啊 @zouyx

如果你需要的是所有 yml 的内容，原来是有个 content 的方法，v3.2.0 可以拿到
```
agollo.GetConfig(namespace).GetContent(storage.ConfigFileFormat(format))
```

**Comment by guaosi** [comment]
@zouyx 
我的想法是，配置中心是json格式，那么本地同步下来，也是json格式，json文件。
配置中心是yml格式，那么本地同步下来，也是yml格式，yml文件。
这样才合理吧。
本地同步到的配置中心文件，应该是直接可用才对，并且不应该出现多余的信息。
我目前临时的解决办法是监听事件监听到后，重新写一个文件，将json转yml，对应的服务组件再来读这个文件。这样实在是太不优雅了。
不知道目前是做到什么程度了，有没有往这个方向做。如果没有的话，我这个迭代有3个sp，可以分出来改善一下。
希望多一点注释，代码到处跳，到处debug我头都疼了

**Comment by zouyx** [comment]
> @zouyx
> 我的想法是，配置中心是json格式，那么本地同步下来，也是json格式，json文件。
> 配置中心是yml格式，那么本地同步下来，也是yml格式，yml文件。
> 这样才合理吧。
> 本地同步到的配置中心文件，应该是直接可用才对，并且不应该出现多余的信息。
> 我目前临时的解决办法是监听事件监听到后，重新写一个文件，将json转yml，对应的服务组件再来读这个文件。这样实在是太不优雅了。
> 不知道目前是做到什么程度了，有没有往这个方向做。如果没有的话，我这个迭代有3个sp，可以分出来改善一下。
> 希望多一点注释，代码到处跳，到处debug我头都疼了

配置中心是什么格式，理论上，下载后就是什么格式。现在之前因为反序列化只支持 json 所以 yml 下载下来不能直接使用。3.3.0 这个版本我增加了 yml 反序列化。但是这个兄弟提的 bug，是因为之前接口遗留下来的问题导致不能直接使用，我这个 pr 也是修复问题，让其能先用。因为如果要改接口，要改或者兼容的地方可能有点多。
