### ISSUE TITLE
能否把demo备注被写详细点呢? 我这找半天没找到监听配置更新的方法

### ISSUE THREAD

**Issue by songangweb** [zouyx/agollo#119]
我这找半天没找到监听配置更新的方法

**Comment by zouyx** [comment]
https://github.com/zouyx/agollo/wiki/%E7%9B%91%E5%90%AC%E5%8F%98%E6%9B%B4%E4%BA%8B%E4%BB%B6

你要的是这个么？

**Comment by songangweb** [comment]
是的,谢谢    
建议整个完全版本的调用demo.   
像Features 里写的功能, 因为想快速接入agollo,没读源码,找调用demo 找半天

**Comment by zouyx** [comment]
> 是的,谢谢
> 建议整个完全版本的调用demo.
> 像Features 里写的功能, 因为想快速接入agollo,没读源码,找调用demo 找半天

你有没有什么好的想法如何改进？能不能从用户角度再提供一点信息？

**Comment by songangweb** [comment]
https://www.cnblogs.com/FireworksEasyCool/p/12710325.html

这个博客的文章写的接入demo,觉得写的挺好,你可以参考一下

**Comment by zouyx** [comment]
感谢，我先参考一下。

**Comment by zouyx** [comment]
@songangweb ，我看了一下，确实是有问题，应该是之前重构移过包。把原来的方法移走了，demo我也优化过了一下。

https://github.com/zouyx/agollo_demo
