### ISSUE TITLE
[BUG] InitSyncServerIPList should  initialize synchronously and update in anothor goroutine

### ISSUE THREAD

**Issue by lenghan4real** [zouyx/agollo#122]
**请简单描述bug的场景**
First sync should happens after `ServerIPList` fetched successfully.

```
func loadBalance(appConfig *config.AppConfig) string {
	if !appConfig.IsConnectDirectly() {
		return appConfig.GetHost()
	}
        //.....
}
```
In some scenario, `appConfig.GetHost()` is only used for lookup. It's backing by a proxy, topically Nginx(which may not support HTTP long polling by default).

**如何重现**

再现行为的步骤：

1.跳到“…”

2.点击“…”

3.向下滚动到“…”

4.见错误

**期望**
请描述期望发生什么

**截图**
如有

**Agollo 版本 :**

**日志信息**

**其他上下文**
如有

**Comment by zouyx** [comment]
@lenghan4real 收到，我检查一下

**Comment by zouyx** [comment]
你好，我看了下，我好像不是太明白该问题的意思是？你的意思是：因为现在 `ServerIPList ` 是异步的，第一次更新的时候因为是用域名来同步，所以走了 nginx，nginx 不支持 long poll 所以导致第一次同步失败，这个意思么？
