### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Pineana** [zouyx/agollo#125]
**请简单描述bug的场景**
在使用监听方法时，onchange接受的changeEvent的值总会慢一次发布

**如何重现**
```
func main(){
	c := &config.AppConfig{
		AppID:            "0001",
		Cluster:          "dev",
		NamespaceName:    "application",
		IP:               "http://112.124.105.192:8180",
		IsBackupConfig:   false,
		Secret:           "3b9233edc4ab4b8f802f1907f80de344",
	}
	agollo.InitCustomConfig(func() (*config.AppConfig, error) {
		return c,nil
	})
	agollo.AddChangeListener(&CustomChangeListener{})
	err:=agollo.Start()
	if err != nil {
		fmt.Println(err.Error())
	}

	r :=gin.Default()
	r.GET("/seek",seek)
	r.Run(":8080")
}

type CustomChangeListener struct {

}

func (c *CustomChangeListener) OnChange(changeEvent *storage.ChangeEvent) {
	fmt.Println(changeEvent.Namespace)
	fmt.Printf("%#v\n",changeEvent.Changes["demo"])
	fmt.Printf("%#v",changeEvent.Changes["notice"])
}
```

再现行为的步骤：
apollo 更新后点击发布
客户端监听到改变后调用Onchange方法
但是Onchange显示的变更总会慢发布一个版本。

**截图**
如有
<img width="970" alt="截屏2020-07-07 下午2 41 52" src="https://user-images.githubusercontent.com/28687530/86730163-d0c22800-c060-11ea-9bd3-399dc9f7ae61.png">

apollo服务端发布后，demo的值已经变更
但是客户端监听到的变化为
<img width="800" alt="截屏2020-07-07 下午2 49 00" src="https://user-images.githubusercontent.com/28687530/86730368-0830d480-c061-11ea-8a9e-bb24cb7da1a4.png">
只有在下次发布时客户端才会显示上一次的变更

**Agollo 版本 :**

**日志信息**

**其他上下文**
如有

**Comment by zouyx** [comment]
#124

**Comment by zouyx** [comment]
我看了下是这个  pr 改错了，我下午发布一下修复版本

https://github.com/zouyx/agollo/pull/121/files#diff-6cb6d372a9fae60247d10932bda64544R261

**Comment by zouyx** [comment]
@Pineana 你试试是否可以

https://github.com/zouyx/agollo/releases/tag/v3.4.2

**Comment by zouyx** [comment]
如果还有问题可以 reopen
