### ISSUE TITLE
[BUG] 无法获取关联到公共namespace的配置

### ISSUE THREAD

**Issue by telanflow** [zouyx/agollo#130]
**请简单描述bug的场景**
Appid：master   下面 有一个公共namespace：redis

Appid：ip-server 下面添加了一个关联的namespace：redis（关联到master下的redis），

此时：
```
       // 启动
       agollo.InitCustomConfig(func() (*apolloCfg.AppConfig, error) {
		return &apolloCfg.AppConfig{
			AppID:         "ip-server",
			Cluster:       "default",
			NamespaceName: "application, redis",
			IP:            "**********",
			IsBackupConfig: false,
		}, nil
	})
        agollo.start()

        // 获取不到配置
        cache := agollo.GetConfigCache("redis")
	cache.Range(func(key, value interface{}) bool {
		logger.Infof("%s  %s", key, value)
		return true
	})
```

**Agollo 版本 :**
 - Version 3.4.4

**Comment by telanflow** [comment]
application下的配置项能正常获取到，是我的操作方式有问题吗？

**Comment by zouyx** [comment]
https://github.com/zouyx/agollo_demo/tree/master/helloworld，你可以直接运行这个 samples 尝试一下，其中的 namespace 就是关联过来。

登录方式：https://github.com/ctripcorp/apollo#apollo---a-reliable-configuration-management-system

**Comment by telanflow** [comment]
@zouyx 
我知道原因了！
因为配置namespace的时候多了个空格造成的：
```
// application 和 redis 之间多了个空格
NamespaceName: "application, redis",
```

Wiki文档误导了我，
[使用指南](https://github.com/zouyx/agollo/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)

“多namespace配置“  这一栏修改一下，把空格去掉
```
{
    "appId": "test",
    "cluster": "dev",
    "namespaceName": "application, applications1",
    "ip": "localhost:8888"
}
```

**Comment by zouyx** [comment]
> @zouyx
> 我知道原因了！
> 因为配置namespace的时候多了个空格造成的：
> 
> ```
> // application 和 redis 之间多了个空格
> NamespaceName: "application, redis",
> ```
> 
> Wiki文档误导了我，
> [使用指南](https://github.com/zouyx/agollo/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)
> 
> “多namespace配置“ 这一栏修改一下，把空格去掉
> 
> ```
> {
>     "appId": "test",
>     "cluster": "dev",
>     "namespaceName": "application, applications1",
>     "ip": "localhost:8888"
> }
> ```

如果你可以帮忙修改下代码 trim 一下更好，哈哈。

**Comment by zouyx** [comment]
> @zouyx
> 我知道原因了！
> 因为配置namespace的时候多了个空格造成的：
> 
> ```
> // application 和 redis 之间多了个空格
> NamespaceName: "application, redis",
> ```
> 
> Wiki文档误导了我，
> [使用指南](https://github.com/zouyx/agollo/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)
> 
> “多namespace配置“ 这一栏修改一下，把空格去掉
> 
> ```
> {
>     "appId": "test",
>     "cluster": "dev",
>     "namespaceName": "application, applications1",
>     "ip": "localhost:8888"
> }
> ```

已修改。如无其他问题可以 close 一下

**Comment by telanflow** [comment]
哈哈，好的。感谢！ @zouyx
