### ISSUE TITLE
[BUG]如果value不为string时，会产生panic

### ISSUE THREAD

**Issue by ichiro999** [zouyx/agollo#138]
**请简单描述bug的场景**
apollo的namespace使用json或yaml格式，新版本的agollo客户端会解析成key，value缓存，如果apollo里的value为int，bool类型时，在调用GetIntValue时会奔溃，说interface类型为int/bool类型 ，不是string类型，

**Comment by zouyx** [comment]
收到，我周末抽时间检查一下

**Comment by zouyx** [comment]
是个bug，但是 default namespace 应该是不允许使用private 的类型，`defaultNamespace = "application"`，你是怎么做到的😆

**Comment by ichiro999** [comment]
代码已经把yaml或者json做解析存储了，解析工具可以解析成具体具体类型，所以就有这个问题，但是对于key=value类型的默认都当做字符串所以接口没有问题，至于不允许使用private类型是什么意思？

**Comment by zouyx** [comment]
> 代码已经把yaml或者json做解析存储了，解析工具可以解析成具体具体类型，所以就有这个问题，但是对于key=value类型的默认都当做字符串所以接口没有问题，至于不允许使用private类型是什么意思？

我目测是重构的时候没改，getIntvalue 那种只支持默认的 namespace

**Comment by ichiro999** [comment]
但是可以通过GetConfig获取不同namespace，然后去GetIntValue，这时候就不是默认的

**Comment by ichiro999** [comment]
或者这bug我来修复，你assign给我？

**Comment by ichiro999** [comment]
> > 代码已经把yaml或者json做解析存储了，解析工具可以解析成具体具体类型，所以就有这个问题，但是对于key=value类型的默认都当做字符串所以接口没有问题，至于不允许使用private类型是什么意思？
> 
> 我目测是重构的时候没改，getIntvalue 那种只支持默认的 namespace

但是可以通过GetConfig获取不同namespace，然后去GetIntValue，这时候就不是默认的。或者这bug我来修复，你assign给我？

**Comment by ichiro999** [comment]
> > 代码已经把yaml或者json做解析存储了，解析工具可以解析成具体具体类型，所以就有这个问题，但是对于key=value类型的默认都当做字符串所以接口没有问题，至于不允许使用private类型是什么意思？
> 
> 我目测是重构的时候没改，getIntvalue 那种只支持默认的 namespace

但是可以通过GetConfig获取不同namespace，然后去GetIntValue，这时候就不是默认的。或者这bug我来修复，你assign给我？
