### ISSUE TITLE
[FEATURE]当前使用的viper库版本可能存在风险

### ISSUE THREAD

**Issue by 18761692867** [zouyx/agollo#139]
**功能适用的场景？**
该功能适用于开发、灰度场景

**你需要的功能是否有关联问题？**
简明扼要地描述你需要的功能，当 [项目使用中同时使用viper库与apollo库时，goland会自动选择viper 1.7.1版本，这是由于apollo 3.4.5使用了viper 1.7.1。viper 1.7.1版本在一些安全监测中被认为是高风险版本，而多人开发中很难每次commit都注意版本控制，导致项目被安全监测pass]

**你期望的解决方案是？**
我期望改造apollo的go.mod中选择viper1.7.0版本后，实现安全监测的通行，十分感谢作者的维护

**Comment by zouyx** [comment]
> **功能适用的场景？**
> 该功能适用于开发、灰度场景
> 
> **你需要的功能是否有关联问题？**
> 简明扼要地描述你需要的功能，当 [项目使用中同时使用viper库与apollo库时，goland会自动选择viper 1.7.1版本，这是由于apollo 3.4.5使用了viper 1.7.1。viper 1.7.1版本在一些安全监测中被认为是高风险版本，而多人开发中很难每次commit都注意版本控制，导致项目被安全监测pass]
> 
> **你期望的解决方案是？**
> 我期望改造apollo的go.mod中选择viper1.7.0版本后，实现安全监测的通行，十分感谢作者的维护

十分感谢兄弟的反馈，是否有具体的风险信息，我查看一下。

鉴于目前情况，有一种解决方案，如下：

在你项目的 go.mod 使用 replace 关键字修改 viper 的版本，如下

```go
replace github.com/spf13/viper v1.7.1 => github.com/spf13/viper v1.7.0
```

**Comment by zouyx** [comment]
@18761692867 我使用 github 的安全扫描是没有扫出任何安全风险，结果如下：

https://github.com/zouyx/viper/security/code-scanning

**Comment by 18761692867** [comment]
@zouyx 我这边也确认了一下，这么看是安全监测那边没有导入lisence导致的问题，麻烦您啦^^
