### ISSUE TITLE
[feat] 能否增加对某个key的事件回调

### ISSUE THREAD

**Issue by Adol1111** [zouyx/agollo#14]
在某些情况下，部分key仅仅知道结果是不够的，可能还需要针对不同的事件做一些初始化操作，比如新增/更新key，或者删除某个key

看了下java的客户端是有这个功能的，能否在go里也增加同样的功能
https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#312-%E7%9B%91%E5%90%AC%E9%85%8D%E7%BD%AE%E5%8F%98%E5%8C%96%E4%BA%8B%E4%BB%B6

**Comment by zouyx** [comment]
@Adol1111 我分析下，看看怎么弄，介意我问一下，你现在有什么场景下会使用得到吗？

**Comment by Adol1111** [comment]
举个例子，比如有个限流器，需要读取配置中心的值然后初始化令牌桶的生成速率、最大容量等等参数。管理员可以针对不同的时段、活动，根据线上的压力动态的调整这个值。客户端收到节点变化的通知，就会重新初始化这个限流器。当某个key删除的时候或enable设置为false，我就会停止限流。

又比如数据库配置更新了，我需要重新初始化一个连接池，并把老的连接池释放掉等等。这种用事件通知是最简单的，虽然可以用其他的方式处理，但是总归会比较麻烦一些。

**Comment by Adol1111** [comment]
补充：前面限流器的场景，虽然可以不做初始化操作，每次比较的时候根据读到的配置动态调整也是可行的。但是，如果我使用的是第三方库，这就需要主动把配置中心的客户端代码嵌入到别人的代码里，做二次开发，会相对比较麻烦。如果类库更新了，也不能直接升级。

**Comment by zouyx** [comment]
@Adol1111 理解了，谢谢。

**Comment by zouyx** [comment]
@Adol1111 可以试用下，有问题再反馈

监听变更事件（阻塞）
```go
func main() {
	event := agollo.ListenChangeEvent()
	changeEvent := <-event
	bytes, _ := json.Marshal(changeEvent)
	fmt.Println("event:", string(bytes))
}
```

**Comment by Adol1111** [comment]
好的，感谢，我等下去试试看
