### ISSUE TITLE
你好,能在批量的增删改查功能吗？

### ISSUE THREAD

**Issue by feixia5712** [zouyx/agollo#141]

**Comment by zouyx** [comment]
你好，你想要这个功能吗？

https://github.com/ctripcorp/apollo/wiki/Apollo%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0

**Comment by feixia5712** [comment]
嗯，基本是这个功能

**Comment by zouyx** [comment]
> 嗯，基本是这个功能

知道了，我之前也有计划搞个。

**Comment by feixia5712** [comment]
哦，那好的，希望作者有空尽快搞下,造福大众

**Comment by in-the-sky-a** [comment]
@zouyx  目前 agollo 还不支持 更新和release 配置吗？

**Comment by zouyx** [comment]
> @zouyx 目前 agollo 还不支持 更新和release 配置吗？

agollo 目前只读，这个月我希望能提供个支持 open-API 的 client
