### ISSUE TITLE
[BUG]3.4.1

### ISSUE THREAD

**Issue by ohmygd** [zouyx/agollo#142]
**请简单描述bug的场景**
zouyx版本3.4.1
go版本1.13

listener := &apolloListener{}
agollo.AddChangeListener(listener)

注册监听
我的场景： 
apollo里面只设置1个值，int类型， 然后修改apollo并不会立即生效，代码里面貌似没有收到改动通知
如果apollo里面设置了2个值， 那么改动， 代码里面可以收到改动通知
虽然zouyx有66s兜底，更新apollo本地缓存

**如何重现**
apollo里面只设置1个int类型

**期望**
1个值 变动应该也能立即生效

**截图**
如有
![image](https://user-images.githubusercontent.com/19659483/93959243-d3dcd280-fd8a-11ea-815b-e6fbb53c756d.png)

![image](https://user-images.githubusercontent.com/19659483/93959262-e0612b00-fd8a-11ea-9e05-2dd532a2a742.png)
如上图所示，39s改动后，代码里的值还是2

![image](https://user-images.githubusercontent.com/19659483/93959331-05559e00-fd8b-11ea-95c1-47949352ab43.png)

![image](https://user-images.githubusercontent.com/19659483/93959345-0b4b7f00-fd8b-11ea-803d-0f97b8bb55c3.png)

如果apollo里面有2个值的话， 那么变动就会立即生效了

**Agollo 版本 :**
 - Version 3.4.1

**Comment by zouyx** [comment]
@ohmygd 我试了下最新版本好像木有这个问题，是否可以尝试下？
