### ISSUE TITLE
可以自定义nofityConnectTimeout[FEATURE]

### ISSUE THREAD

**Issue by sp56** [zouyx/agollo#143]
**功能适用的场景？**
如果把需要的namespace写错之类的，timeout时间定的太长了。一直卡着

补充：
看到代码：
`
for {
		host := loadBalance(appConfig)
		if host == "" {
			return nil, err
		}

		requestURL := fmt.Sprintf(format, host, connectConfig.URI)
		response, err = Request(requestURL, connectConfig, callBack)
		if err == nil {
			return response, err
		}

		env.SetDownNode(host)
	}
`
如果在这个位置出错就一直卡这里了，比如上面我说的写了一个存在的 namesapce

这里又延伸出一个问题，既然我在配置文件中 定义了自己需要的 namespace，是否考虑在初始化配置之后，对手动输入的namespace进行拦截呢？

**Comment by zouyx** [comment]
@sp56 请问你用的是什么版本？

**Comment by sp56** [comment]
> @sp56 请问你用的是什么版本？

github.com/zouyx/agollo/v3 v3.4.5

**Comment by sp56** [comment]
@zouyx 
github.com/zouyx/agollo/v3 v3.4.5

**Comment by zouyx** [comment]
> @zouyx
> github.com/zouyx/agollo/v3 v3.4.5

**Comment by zouyx** [comment]
4.x 应该没有这个问题，修改了获取的方式
