### ISSUE TITLE
concurrent map writes

### ISSUE THREAD

**Issue by crossgo** [zouyx/agollo#144]
使用V4的时候，如果加载多个namespace会出现data race，而且网络不顺的时候，容易出现panic的报错
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 80 [running]:
runtime.throw(0x1530186, 0x15)
	D:/Go1.14/src/runtime/panic.go:1116 +0x64 fp=0x15d63dbc sp=0x15d63da8 pc=0x433124
runtime.mapassign_faststr(0x13367a0, 0x1516e720, 0x155dcac0, 0x1c, 0x2)
	D:/Go1.14/src/runtime/map_faststr.go:291 +0x358 fp=0x15d63df8 sp=0x15d63dbc pc=0x410ed8
github.com/zouyx/agollo/v4/env/file/json.(*FileHandler).GetConfigFile(0x36bd128, 0x0, 0x0, 0x155dc8e0, 0x18, 0x155dcac0, 0x1c, 0x150532c0, 0x4aa0df8)
	D:/Go/bin/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/env/file/json/json.go:58 +0x2ee fp=0x15d63e44 sp=0x15d63df8 pc=0xd83d0e
github.com/zouyx/agollo/v4/env/file/json.(*FileHandler).LoadConfigFile(0x36bd128, 0x0, 0x0, 0x155dc8e0, 0x18, 0x155dcac0, 0x1c, 0x1, 0x15587418, 0x0)
	D:/Go/bin/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/env/file/json/json.go:66 +0x55 fp=0x15d63e84 sp=0x15d63e44 pc=0xd83da5
github.com/zouyx/agollo/v4/component/remote.loadBackupConfig.func1(0x155dcac0, 0x1c)
	D:/Go/bin/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/component/remote/async.go:147 +0x62 fp=0x15d63ec4 sp=0x15d63e84 pc=0xd7fa02
github.com/zouyx/agollo/v4/env/config.SplitNamespaces(0x155dcac0, 0x1c, 0x15d63f38, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	D:/Go/bin/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/env/config/config.go:119 +0x120 fp=0x15d63f08 sp=0x15d63ec4 pc=0xd7ac00
github.com/zouyx/agollo/v4/component/remote.loadBackupConfig(0x155dcac0, 0x1c, 0x155c1560, 0x0, 0x0, 0x0)
	D:/Go/bin/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/component/remote/async.go:146 +0x9d fp=0x15d63f48 sp=0x15d63f08 pc=0xd7ed9d
github.com/zouyx/agollo/v4/component/remote.(*asyncApolloConfig).Sync(0x1515fb88, 0x155c1560, 0x0, 0x0, 0x0)
	D:/Go/bin/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/component/remote/async.go:74 +0x1b1 fp=0x15d63fb4 sp=0x15d63f48 pc=0xd7e7e1
github.com/zouyx/agollo/v4/component/notify.(*ConfigComponent).Start(0x15286238)
	D:/Go/bin/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/component/notify/componet_notify.go:56 +0xfd fp=0x15d63fe0 sp=0x15d63fb4 pc=0xd8320d
github.com/zouyx/agollo/v4/component.StartRefreshConfig(0x1787ab0, 0x15286238)
	D:/Go/bin/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/component/common.go:27 +0x25 fp=0x15d63fe8 sp=0x15d63fe0 pc=0xd7c255
runtime.goexit()
	D:/Go1.14/src/runtime/asm_386.s:1337 +0x1 fp=0x15d63fec sp=0x15d63fe8 pc=0x45f811
created by github.com/zouyx/agollo/v4.StartWithConfig
	D:/Go/bin/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/client.go:110 +0x217

goroutine 1 [select, 256 minutes]:
github.com/micro/go-micro/v2/web.(*service).Run(0x154a3420, 0x0, 0x0)
	D:/Go/bin/pkg/mod/github.com/micro/go-micro/v2@v2.9.1/web/service.go:469 +0x29a
hummingbird.api/internal/app/api/frontend.initService(0x17b1ea0, 0x154e6000)
	D:/GoPath/src/hummingbird.api/internal/app/api/frontend/main.go:102 +0x5f5
hummingbird.api/internal/app/api/frontend.Main()
	D:/GoPath/src/hummingbird.api/internal/app/api/frontend/main.go:64 +0x175
main.main()
	D:/GoPath/src/hummingbird.api/cmd/api/frontend/main.go:6 +0x17

goroutine 7 [select, 256 minutes]:
github.com/micro/go-micro/v2/config/loader/memory.(*watcher).Next(0x15388000, 0x13, 0x155dc1a0, 0x13)
	D:/Go/bin/pkg/mod/github.com/micro/go-micro/v2@v2.9.1/config/loader/memory/memory.go:393 +0xc1
github.com/micro/go-micro/v2/config.(*config).run.func1(0x17913b0, 0x15388000, 0x15382040, 0x15108dc0)
	D:/Go/bin/pkg/mod/github.com/micro/go-micro/v2@v2.9.1/config/default.go:82 +0x30
github.com/micro/go-micro/v2/config.(*config).run(0x15108dc0)
	D:/Go/bin/pkg/mod/github.com/micro/go-micro/v2@v2.9.1/config/default.go:123 +0xfa
created by github.com/micro/go-micro/v2/config.newConfig
	D:/Go/bin/pkg/mod/github.com/micro/go-micro/v2@v2.9.1/config/default.go:37 +0x69

goroutine 18 [chan receive, 256 minutes]:
github.com/micro/go-micro/v2/config/loader/memory.(*memory).Watch.func1(0x15388000, 0x15314300, 0x1538a000)
	D:/Go/bin/pkg/mod/github.com/micro/go-micro/v2@v2.9.1/config/loader/memory/memory.go:360 +0x2f
created by github.com/micro/go-micro/v2/config/loader/memory.(*memory).Watch
	D:/Go/bin/pkg/mod/github.com/micro/go-micro/v2@v2.9.1/config/loader/memory/memory.go:359 +0x1b4

goroutine 19 [select, 256 minutes]:
github.com/micro/go-micro/v2/config.(*config).run.func2(0x15382040, 0x15108dc0, 0x17913b0, 0x15388000)
	D:/Go/bin/pkg/mod/github.com/micro/go-micro/v2@v2.9.1/config/default.go:115 +0x78
created by github.com/micro/go-micro/v2/config.(*config).run
	D:/Go/bin/pkg/mod/github.com/micro/go-micro/v2@v2.9.1/config/default.go:114 +0xe1

goroutine 9 [select]:
github.com/patrickmn/go-cache.(*janitor).Run(0x1540a0d0, 0x1508c150)
	D:/Go/bin/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1079 +0xa6
created by github.com/patrickmn/go-cache.runJanitor
	D:/Go/bin/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1099 +0x98

goroutine 10 [select]:
github.com/patrickmn/go-cache.(*janitor).Run(0x1540a100, 0x1508c1b0)
	D:/Go/bin/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1079 +0xa6
created by github.com/patrickmn/go-cache.runJanitor
	D:/Go/bin/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1099 +0x98

goroutine 37 [select, 256 minutes]:
github.com/micro/go-micro/v2/config/source/file.(*watcher).Next(0x15004130, 0x13df0e0, 0x0, 0x1549a300)
	D:/Go/bin/pkg/mod/github.com/micro/go-micro/v2@v2.9.1/config/source/file/watcher.go:43 +0xf4
github.com/micro/go-micro/v2/config/loader/memory.(*memory).watch.func1(0x0, 0x17913d0, 0x15004130, 0x15314300, 0x17913d0)
	D:/Go/bin/pkg/mod/github.com/micro/go-micro/v2@v2.9.1/config/loader/memory/memory.go:54 +0x4a
github.com/micro/go-micro/v2/config/loader/memory.(*memory).watch(0x15314300, 0x0, 0x179cf40, 0x1538ab20)
	D:/Go/bin/pkg/mod/github.com/micro/go-micro/v2@v2.9.1/config/loader/memory/memory.go:104 +0xe6
created by github.com/micro/go-micro/v2/config/loader/memory.(*memory).Load
	D:/Go/bin/pkg/mod/github.com/micro/go-micro/v2@v2.9.1/config/loader/memory/memory.go:324 +0x25f

goroutine 13 [syscall, 248 minutes, locked to thread]:
syscall.Syscall6(0x76eb31a0, 0x5, 0x23c, 0x15055e6c, 0x15055e70, 0x15055ea8, 0xffffffff, 0x0, 0x0, 0x0, ...)
	D:/Go1.14/src/runtime/syscall_windows.go:201 +0xbb
syscall.GetQueuedCompletionStatus(0x23c, 0x15055e6c, 0x15055e70, 0x15055ea8, 0xffffffff, 0x0, 0x0)
	D:/Go1.14/src/syscall/zsyscall_windows.go:556 +0x83
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0x153882a0)
	D:/Go/bin/pkg/mod/github.com/fsnotify/fsnotify@v1.4.7/windows.go:381 +0x72
created by github.com/fsnotify/fsnotify.NewWatcher
	D:/Go/bin/pkg/mod/github.com/fsnotify/fsnotify@v1.4.7/windows.go:46 +0x1a5

goroutine 22 [select, 256 minutes]:
github.com/micro/go-micro/v2/config/loader/memory.(*memory).watch.func2(0x1549a340, 0x15314300, 0x17913d0, 0x15004130)
	D:/Go/bin/pkg/mod/github.com/micro/go-micro/v2@v2.9.1/config/loader/memory/memory.go:96 +0x78
created by github.com/micro/go-micro/v2/config/loader/memory.(*memory).watch
	D:/Go/bin/pkg/mod/github.com/micro/go-micro/v2@v2.9.1/config/loader/memory/memory.go:95 +0xc5

goroutine 38 [chan receive, 17 minutes]:
github.com/zouyx/agollo/v4/component/serverlist.(*SyncServerIPListComponent).Start(0x155bfae8)
	D:/Go/bin/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/component/serverlist/sync.go:59 +0xef
github.com/zouyx/agollo/v4/component.StartRefreshConfig(0x1787ad0, 0x155bfae8)
	D:/Go/bin/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/component/common.go:27 +0x25
created by github.com/zouyx/agollo/v4/component/serverlist.InitSyncServerIPList
	D:/Go/bin/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/component/serverlist/sync.go:42 +0x5b

goroutine 9754 [select]:
net/http.(*persistConn).writeLoop(0x157b60a0)
	D:/Go1.14/src/net/http/transport.go:2277 +0xdd
created by net/http.(*Transport).dialConn
	D:/Go1.14/src/net/http/transport.go:1648 +0xa5c

**Comment by zouyx** [comment]
好的，这周内我定位一下并将其修复

**Comment by zouyx** [comment]
我明天会发布一版

**Comment by zouyx** [comment]
@crossgo https://github.com/zouyx/agollo/releases/tag/v4.0.1
测试报告：https://github.com/zouyx/agollo_demo/actions/runs/361189009

**Comment by zhanghuizong** [comment]
我也碰到了
==================
WARNING: DATA RACE
Read at 0x00c0000cc330 by goroutine 21:
  github.com/zouyx/agollo/v4/component/remote.(*asyncApolloConfig).notifyRemoteConfig()
      C:/Users/go/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/component/remote/async.go:105 +0xde
  github.com/zouyx/agollo/v4/component/remote.(*asyncApolloConfig).Sync()
      C:/Users/go/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/component/remote/async.go:70 +0x6c
  github.com/zouyx/agollo/v4/component/notify.(*ConfigComponent).Start()
      C:/Users/go/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/component/notify/componet_notify.go:56 +0x1ee
  github.com/zouyx/agollo/v4/component.StartRefreshConfig()
      C:/Users/go/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/component/common.go:27 +0x45

**Comment by zouyx** [comment]
> component/remote/async.go:105

你配置了多少个 namespace？

**Comment by zouyx** [comment]
> # 我也碰到了
> WARNING: DATA RACE
> Read at 0x00c0000cc330 by goroutine 21:
> github.com/zouyx/agollo/v4/component/remote.(*asyncApolloConfig).notifyRemoteConfig()
> C:/Users/go/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/component/remote/async.go:105 +0xde
> github.com/zouyx/agollo/v4/component/remote.(*asyncApolloConfig).Sync()
> C:/Users/go/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/component/remote/async.go:70 +0x6c
> github.com/zouyx/agollo/v4/component/notify.(*ConfigComponent).Start()
> C:/Users/go/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/component/notify/componet_notify.go:56 +0x1ee
> github.com/zouyx/agollo/v4/component.StartRefreshConfig()
> C:/Users/go/pkg/mod/github.com/zouyx/agollo/v4@v4.0.0-rc1/component/common.go:27 +0x45

是否能提供一下出问题的 demo？
