### ISSUE TITLE
apollo服务端无法访问，如何使用本地缓存的配置文件呢

### ISSUE THREAD

**Issue by panyaowei** [zouyx/agollo#148]
如题

**Comment by zouyx** [comment]
如果第一次启动成功拉取配置，会缓存到本地。如果在后续获取配置失败即会读取该配置。可以在程序或者配置文件中，使用以下配置：https://github.com/zouyx/agollo_demo/search?q=backup

**Comment by panyaowei** [comment]
> 如果第一次启动成功拉取配置，会缓存到本地。如果在后续获取配置失败即会读取该配置。可以在程序或者配置文件中，使用以下配置：https://github.com/zouyx/agollo_demo/search?q=backup
IsBackupConfig  这个配置项设置为ture是吧

**Comment by zouyx** [comment]
> > 如果第一次启动成功拉取配置，会缓存到本地。如果在后续获取配置失败即会读取该配置。可以在程序或者配置文件中，使用以下配置：https://github.com/zouyx/agollo_demo/search?q=backup
> > 如果我第二次启动项目，获取配置失败后，他会等一分钟后在去加载本地先前成功拉取的配置。  是否有提供API能让项目一启动就先去加载本地的配置。。  不然都等了一分钟再去加载。我读取配置的方法都会返回空

你用的是什么版本？新版本好像没有等待这个操作？或者你能帮忙 debug 下在哪里有等待么

https://github.com/zouyx/agollo/blob/ae9aad86116f12c5d747585aba7f2f6dc67737f0/client.go#L99

**Comment by panyaowei** [comment]
> > > 如果第一次启动成功拉取配置，会缓存到本地。如果在后续获取配置失败即会读取该配置。可以在程序或者配置文件中，使用以下配置：https://github.com/zouyx/agollo_demo/search?q=backup
> > > 如果我第二次启动项目，获取配置失败后，他会等一分钟后在去加载本地先前成功拉取的配置。  是否有提供API能让项目一启动就先去加载本地的配置。。  不然都等了一分钟再去加载。我读取配置的方法都会返回空
> 
> 你用的是什么版本？新版本好像没有等待这个操作？或者你能帮忙 debug 下在哪里有等待么
> 
> https://github.com/zouyx/agollo/blob/ae9aad86116f12c5d747585aba7f2f6dc67737f0/client.go#L99

我用的是v4。得等一分钟才会去加载本地的缓存。以下是我的打印日志

2020-11-26 16:01:50.5554219 +0800 CST m=+2.100492601
[[Connect Apollo Server Fail,url:%s,StatusCode:%s http://xxxxxx:8080/notifications/v2?appId=xxxxxxxxxxxx 400]]
[[Over Max Retry Still Error,Error: <nil>]]
[[load config file from : ./pan/panyaowei_test-IVM.PANPAN.json]]
[[load config file from : ./pan/panyaowei_test-global.register.center.json]]
[[load config file from : ./pan/panyaowei_test-panyaowei_test.json]]
加载到缓存文件的配置
2020-11-26 16:02:52.6772907 +0800 CST m=+64.222467801

**Comment by zouyx** [comment]
> > > > 如果第一次启动成功拉取配置，会缓存到本地。如果在后续获取配置失败即会读取该配置。可以在程序或者配置文件中，使用以下配置：https://github.com/zouyx/agollo_demo/search?q=backup
> > > > 如果我第二次启动项目，获取配置失败后，他会等一分钟后在去加载本地先前成功拉取的配置。  是否有提供API能让项目一启动就先去加载本地的配置。。  不然都等了一分钟再去加载。我读取配置的方法都会返回空
> > 
> > 
> > 你用的是什么版本？新版本好像没有等待这个操作？或者你能帮忙 debug 下在哪里有等待么
> > https://github.com/zouyx/agollo/blob/ae9aad86116f12c5d747585aba7f2f6dc67737f0/client.go#L99
> 
> 我用的是v4。得等一分钟才会去加载本地的缓存。以下是我的打印日志
> 
> 2020-11-26 16:01:50.5554219 +0800 CST m=+2.100492601
> [[Connect Apollo Server Fail,url:%s,StatusCode:%s http://xxxxxx:8080/notifications/v2?appId=xxxxxxxxxxxx 400]]
> [[Over Max Retry Still Error,Error: ]]
> [[load config file from : ./pan/panyaowei_test-IVM.PANPAN.json]]
> [[load config file from : ./pan/panyaowei_test-global.register.center.json]]
> [[load config file from : ./pan/panyaowei_test-panyaowei_test.json]]
> 加载到缓存文件的配置
> 2020-11-26 16:02:52.6772907 +0800 CST m=+64.222467801

收到，我晚上模拟下

**Comment by panyaowei** [comment]
> > > > > 如果第一次启动成功拉取配置，会缓存到本地。如果在后续获取配置失败即会读取该配置。可以在程序或者配置文件中，使用以下配置：https://github.com/zouyx/agollo_demo/search?q=backup
> > > > > 如果我第二次启动项目，获取配置失败后，他会等一分钟后在去加载本地先前成功拉取的配置。  是否有提供API能让项目一启动就先去加载本地的配置。。  不然都等了一分钟再去加载。我读取配置的方法都会返回空
> > > 
> > > 
> > > 你用的是什么版本？新版本好像没有等待这个操作？或者你能帮忙 debug 下在哪里有等待么
> > > https://github.com/zouyx/agollo/blob/ae9aad86116f12c5d747585aba7f2f6dc67737f0/client.go#L99
> > 
> > 
> > 我用的是v4。得等一分钟才会去加载本地的缓存。以下是我的打印日志
> > 2020-11-26 16:01:50.5554219 +0800 CST m=+2.100492601
> > [[Connect Apollo Server Fail,url:%s,StatusCode:%s http://xxxxxx:8080/notifications/v2?appId=xxxxxxxxxxxx 400]]
> > [[Over Max Retry Still Error,Error: ]]
> > [[load config file from : ./pan/panyaowei_test-IVM.PANPAN.json]]
> > [[load config file from : ./pan/panyaowei_test-global.register.center.json]]
> > [[load config file from : ./pan/panyaowei_test-panyaowei_test.json]]
> > 加载到缓存文件的配置
> > 2020-11-26 16:02:52.6772907 +0800 CST m=+64.222467801
> 
> 收到，我晚上模拟下

帅哥，怎么样啦

**Comment by zouyx** [comment]
我看了下，是[同步调用](https://github.com/zouyx/agollo/blob/ae9aad86116f12c5d747585aba7f2f6dc67737f0/component/remote/sync.go#L99)完之后没用去重新加载，是在[异步调用](https://github.com/zouyx/agollo/blob/ae9aad86116f12c5d747585aba7f2f6dc67737f0/component/remote/async.go#L73)的时候加载。

你试试 PR 是否能解决该问题
