### ISSUE TITLE
事件通知结果和期望不同

### ISSUE THREAD

**Issue by Adol1111** [zouyx/agollo#15]
我试了一下事件监听可以用，但是有点问题

1. 我一共有2个key，key1和key2，然后我通过管理平台删除了key1，结果收到通知后，只有key2的update事件，key1直接就没有了，而不是key1的delete事件

2. 我一共2个key，只修改了其中一个key的值，但是两个我都收到了update事件，其中一个的结果old和new是同一个值（这个是个小问题，最好能够优化一下，这样会比较方便，不过如果太复杂的话，自己比较两个值也是可以的）

**Comment by Adol1111** [comment]
@zouyx 第二点 我比较了一下java的客户端，当某个key的value没有变化时（new==old），不会推送这个key事件通知，你看一下怎么改

**Comment by zouyx** [comment]
@Adol1111 ok

**Comment by Adol1111** [comment]
这个可以关了，我已经提交pr了: #17，已经合并了
