### ISSUE TITLE
[FEATURE] V4 版本怎么获取原始的数据，如[]byte格式的，我想直接转成struct，不想用那些get方法。

### ISSUE THREAD

**Issue by zmy366** [zouyx/agollo#152]

**Comment by zouyx** [comment]
你可以选择使用这种方式，开启备份的时候会进入这个方法，你再去维护自己的信息，你看这样可以吗？

https://github.com/zouyx/agollo/blob/ae9aad86116f12c5d747585aba7f2f6dc67737f0/extension/file_test.go#L46

**Comment by zmy366** [comment]
> 你可以选择使用这种方式，开启备份的时候会进入这个方法，你再去维护自己的信息，你看这样可以吗？
> 
> https://github.com/zouyx/agollo/blob/ae9aad86116f12c5d747585aba7f2f6dc67737f0/extension/file_test.go#L46

备份的话，数据的key也是x.y.z这种格式的，不知如何转换。我想要Sync时放在“content”里的数据能获取，原来v3版就能，这个版本直接扔掉了。因为配置信息很多，我的配置是很多小的struct合起来的，原来直接unmarshal就完事了。现在要写很多的get代码，而且稍微变动一些，就得修改这部分代码，原来只要修改对应的struct就完事了。这部分工作量完全可以省的。

**Comment by zouyx** [comment]
> > 你可以选择使用这种方式，开启备份的时候会进入这个方法，你再去维护自己的信息，你看这样可以吗？
> > https://github.com/zouyx/agollo/blob/ae9aad86116f12c5d747585aba7f2f6dc67737f0/extension/file_test.go#L46
> 
> 备份的话，数据的key也是x.y.z这种格式的，不知如何转换。我想要Sync时放在“content”里的数据能获取，原来v3版就能，这个版本直接扔掉了。因为配置信息很多，我的配置是很多小的struct合起来的，原来直接unmarshal就好了。现在要写很多的get代码，而且稍微变动一些，就得修改这部分代码，原来只要修改对应的struct就行了。只需要一个获取原始数据的接口，这部分工作量完全可以省。

write file 那个方法获取到的是 https://github.com/zouyx/agollo/blob/30024a3a55f879d4952498f30aaf9bcdda1c8340/env/config/apollo_config.go#L79，这个，是个 map，你 marshal 再 unmarshal 一下应该就可以得到你需要的 struct？

**Comment by zmy366** [comment]
> [write file](https://github.com/zouyx/agollo/blob/ae9aad86116f12c5d747585aba7f2f6dc67737f0/extension/file_test.go#L32) 这个个方法获取到的是 [https://github.com/zouyx/agollo/blob/30024a3a55f879d4952498f30aaf9bcdda1c8340/env/config/apollo_config.go#L79，这个，是个](https://github.com/zouyx/agollo/blob/30024a3a55f879d4952498f30aaf9bcdda1c8340/env/config/apollo_config.go#L79%EF%BC%8C%E8%BF%99%E4%B8%AA%EF%BC%8C%E6%98%AF%E4%B8%AA) map，你 marshal 再 unmarshal 一下应该就可以得到你需要的 struct？
> 
> 我目测你说的 content 也是在这里里面拿出来的，但是就是个 content 字段。


我的配置struct 类似这样的层层嵌套组合的struct：
`type Config struct{  
   QueuesConfig struct {...} 
  DatabaseConfig  struct{...}

} `

对应的json是类似这样嵌套的的：
`{
    "queues":{
       "rocketmq":“abc“
   }
}`

而agollo的数据经过format之后是变成的kv的格式  “queues.rocketmq”: ”abc“ 的map。
不知道如何转换成我需要的struct格式？

原始数据的content 可以在sync.processJSONFiles 里找到，之后解析完成就扔掉了，config里就不存在content了。
代码如下：
> https://github.com/zouyx/agollo/blob/master/component/remote/sync.go#L64

是否能提供一个方法能获取这个原始的数据，例如把完整的原始数据也放到cache里？

**Comment by zouyx** [comment]
https://github.com/zouyx/agollo_demo/tree/master/custom/file

因为之前 v3 的实现方式不好扩展，所以 v4 是调整过了结构。你可以先尝试一下，你在 apollo 里配置的是 json 类型，这里出来就是你需要的 json 文件，但你需要通过 config.Configurations[content] 获取， `content` 是 apollo 固定的 key，效果是一样。

如下图：

![image](https://user-images.githubusercontent.com/3828072/101128625-06ccfd80-363b-11eb-8291-2ba4481023c5.png)

**Comment by zmy366** [comment]
嗯嗯，抱歉。我测试过了，json可以通过这种方式获取，yaml格式的key会变成x.y.z这种，没有content。

**Comment by zouyx** [comment]
> 嗯嗯，抱歉。我测试过了，json可以通过这种方式获取，yaml格式的key会变成x.y.z这种，没有content。

是可以了吗？yml 是 key 那种，好像 apollo 默认就返回这样，直接转发出来的。

如果可以可以 close 一下，感谢你的使用。

**Comment by zmy366** [comment]
yaml 也是返回content的key-value形式，value里放了原始数据。
但是在processJSONFiles里用你的解析器解析之后就变了。
```
m, err := parser.Parse(configurations[defaultContentKey]) 
```
变成了纯kv的格式，content不在m里
```
apolloConfig.Configurations = m
```
之后就没有了。

还是需要能获取这个数据。

**Comment by zouyx** [comment]
> yaml 也是返回content的key-value形式，value里放了原始数据。
> 但是在processJSONFiles里用你的解析器解析之后就变了。
> 
> ```
> m, err := parser.Parse(configurations[defaultContentKey]) 
> ```
> 
> 变成了纯kv的格式，content不在m里
> 
> ```
> apolloConfig.Configurations = m
> ```
> 
> 之后就没有了。
> 
> 还是需要能获取这个数据。

```
extension.AddFormatParser(constant.DEFAULT, &normal.Parser{})
	extension.AddFormatParser(constant.Properties, &properties.Parser{})
	extension.AddFormatParser(constant.YML, &yml.Parser{})
	extension.AddFormatParser(constant.YAML, &yaml.Parser{})
```

好的，我更新了下那个例子，默认是这些数据反序列化的方式，你可以自己替换。我替换了 yml 的方式，看看是不是你想要的。

**Comment by zmy366** [comment]
我自定义了一个yaml的parser，已解决。
