### ISSUE TITLE
[BUG] 多个NamespaceName，调用函数GetConfigCache，cache为nil

### ISSUE THREAD

**Issue by younglifestyle** [zouyx/agollo#155]
**请简单描述bug的场景**
多个namespace，调用GetConfigCache，cache为nil，代码可测试自Wiki上的示例代码

**Agollo 版本 :**
V4.0.2

**Comment by younglifestyle** [comment]
测试中读取单个是可以的

**Comment by zouyx** [comment]
你试试这个？https://github.com/zouyx/agollo_demo/tree/master/multi/namespace

**Comment by younglifestyle** [comment]
我的问题，我没有认真看demo，
split := strings.Split(c.NamespaceName, ",")
for _, n := range split {
	checkKey(n,client)
}
GetConfigCache是读取的单个NamespaceName，感谢
