### ISSUE TITLE
[FEATURE] 3.4.5 自定义SyncServerIpList中的超时时间

### ISSUE THREAD

**Issue by starry0819** [zouyx/agollo#160]
3.4.5 版本中，SyncServerIpList中 会用到该网络请求配置lei类。但似乎没有自定义Timeout的地方

![image](https://user-images.githubusercontent.com/28822152/109934149-27bef080-7d07-11eb-82e7-4c817280be8a.png)

**Comment by zouyx** [comment]
> 3.4.5 版本中，SyncServerIpList中 会用到该网络请求配置lei类。但似乎没有自定义Timeout的地方
> 
> ![image](https://user-images.githubusercontent.com/28822152/109934149-27bef080-7d07-11eb-82e7-4c817280be8a.png)

好的，我最近比较忙，这几天抽检查一下，如果能帮忙修改，提交 pr 也是比较欢迎的。

**Comment by zouyx** [comment]
SyncServerIpList 1s 不够么？是走内网还是外网的？这个接口返回的信息不多，1s 应该够吧？java也是走默认的。。

**Comment by starry0819** [comment]
这边是在k8s中使用，发现pod第一次网络请求似乎都会比较慢。用了另一种办法，在服务启动前，进行一次无关网络请求避开服务启动这块快速失败的问题。

**Comment by starry0819** [comment]
正常应该也不会有什么问题，恰好我自己这个特定场景出现这种问题。想着如果能支持自定义的话，可能会更好：D

**Comment by starry0819** [comment]
golang接触的时间不长，可能不够熟练，后面会尝试提一个pr。：D

**Comment by zouyx** [comment]
> 正常应该也不会有什么问题，恰好我自己这个特定场景出现这种问题。想着如果能支持自定义的话，可能会更好：D

明白了，我抽个时间尝试以下，是否会在特定场景下出现该类问题，是否能提供以下 k8s 的版本，docker 如果有，也可以。

**Comment by zq350466548** [comment]
我们在使用客户端获取apollo配置时，也是1s超时了，多机部署情况下，一般在k8s上面第一次初始化需要1-3s。
我们的k8s集群运行在aws ec2实例上，ec2实例有网络开销，而k8s集群自身也有网络插件--calico，所以1s不够。
希望大佬可以考虑加一个自定义超时时间的方式。多谢！

**Comment by zouyx** [comment]
> 我们在使用客户端获取apollo配置时，也是1s超时了，多机部署情况下，一般在k8s上面第一次初始化需要1-3s。
> 我们的k8s集群运行在aws ec2实例上，ec2实例有网络开销，而k8s集群自身也有网络插件--calico，所以1s不够。
> 希望大佬可以考虑加一个自定义超时时间的方式。多谢！

好，我这周修改一下。
