### ISSUE TITLE
[FEATURE] 获取原始数据的接口

### ISSUE THREAD

**Issue by imRainChen** [zouyx/agollo#161]
**功能适用的场景？**
直接通过json.Unmarshal解析namespace配置

**Comment by zouyx** [comment]
> **功能适用的场景？**
> 直接通过json.Unmarshal解析namespace配置

我不是太理解你的需求是？你需要的是下面的骚操作吗？

https://github.com/zouyx/agollo_demo/blob/master/custom/file/check.go

**Comment by imRainChen** [comment]
是的，类似这样的操作

**Comment by zouyx** [comment]
> 是的，类似这样的操作

那这个操作是否能满足你？如果可以该问题是否可以 close？
