### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sp56** [zouyx/agollo#163]
**请简单描述bug的场景**

**如何重现**

再现行为的步骤：

1.跳到“…”

2.点击“…”

3.向下滚动到“…”

4.见错误
2021/03/29 15:28:01 Fail to read config file:open app.properties: The system cannot find the file specified.
panic: Fail to read config file:open app.properties: The system cannot find the file specified.

不影响使用，能正常读取到配置

**期望**
既然已经通过闭包函数把配置传进去了，就不需要再检测配置文件了

**截图**

**Agollo 版本 :**
 - Version [v4.0.4]

**日志信息**
![image](https://user-images.githubusercontent.com/19342886/112803078-7f057600-90a5-11eb-84d1-5255a21852c4.png)

**其他上下文**
如有
![image](https://user-images.githubusercontent.com/19342886/112803154-93497300-90a5-11eb-8fb4-7c578937dac8.png)

**Comment by sp56** [comment]
是我自己搞错了

**Comment by zouyx** [comment]
是有问题吗？没有问题可以 close 一下
