### ISSUE TITLE
[BUG]使用HTTP LONG POLLING的获取到NOtificationID已经更新，但是配置同步失败时就会导致实例没法获取最新配置

### ISSUE THREAD

**Issue by ichiro999** [zouyx/agollo#164]
**请简单描述bug的场景**
1. 使用HTTP LONG POLLING的获取到NotificationID已经更新，但是配置同步失败时，由于已经将NotificationID更新到本地，所以就会到会实例没有办法再次后去新的配置，除非手动在更改下apollo中的配置
2. 客户端初始化时只是使用syncApolloConfig拉去配置，但它并没有更新NotificationID，当开启StartRefreshConfig时，第一次sync配置时因为NotificationID不一样导致又来一次配置，此处有点多余浪费资源

**期望**
1. NotificationID的本地更新应该等到配置拉取成功后
2. 客户端初始化时就把最新的NotificationID获取并存储到本地

**Agollo 版本 :**
所有版本都有

**Comment by zouyx** [comment]
好的，收到，我检查一下

**Comment by ichiro999** [comment]
> 好的，收到，我检查一下

我已经提了pr #166 ，请review下

**Comment by zouyx** [comment]
https://github.com/zouyx/agollo/releases/tag/v4.0.5

**Comment by zouyx** [comment]
感谢大佬的贡献。
