### ISSUE TITLE
建议在首页ReadMe.md就直接写好简易的使用文档。

### ISSUE THREAD

**Issue by panol** [zouyx/agollo#165]
**功能适用的场景？**
该功能适用于新手入门场景

**你需要的功能是否有关联问题？**
在首页加入
go get github.com/zouyx/agollo
安装包
以及给出快速使用的代码示例

**你期望的解决方案是？**

**Comment by zouyx** [comment]
> **功能适用的场景？**
> 该功能适用于新手入门场景
> 
> **你需要的功能是否有关联问题？**
> 在首页加入
> go get github.com/zouyx/agollo
> 安装包
> 以及给出快速使用的代码示例
> 
> **你期望的解决方案是？**

我觉得可以，感谢建议。如果你能提交一下 PR 也可以：）

**Comment by zouyx** [comment]
https://github.com/zouyx/agollo/blob/master/README.md

已增加快速入门章节
