### ISSUE TITLE
[BUG]存在无用参数

### ISSUE THREAD

**Issue by byyam** [zouyx/agollo#169]
**请简单描述bug的场景**
在使用`StartWithConfig`根据配置初始化连接Apollo的参数中，`isBackupConfig`填false没用，因为hardcode了true

``` golang
	//first sync
	configs := syncApolloConfig.Sync(c.getAppConfig)
	if len(configs) > 0 {
		for _, apolloConfig := range configs {
			c.cache.UpdateApolloConfig(apolloConfig, c.getAppConfig, true) // isBackupConfig hardcode
		}
	}

```

**Comment by zouyx** [comment]
> **请简单描述bug的场景**
> 在使用`StartWithConfig`根据配置初始化连接Apollo的参数中，`isBackupConfig`填false没用，因为hardcode了true
> 
> ```go
> 	//first sync
> 	configs := syncApolloConfig.Sync(c.getAppConfig)
> 	if len(configs) > 0 {
> 		for _, apolloConfig := range configs {
> 			c.cache.UpdateApolloConfig(apolloConfig, c.getAppConfig, true) // isBackupConfig hardcode
> 		}
> 	}
> ```

感谢，我看了下，是这种情况。我一会修改下。

**Comment by zouyx** [comment]
https://github.com/zouyx/agollo/releases/edit/v4.0.7
