### ISSUE TITLE
连接apollo的配置，是否可以不采用配置文件的方式

### ISSUE THREAD

**Issue by wangkirin** [zouyx/agollo#21]
现在的两个配置文件是必须的，连接apollo的配置，是否可以不采用配置文件的方式，直接通过代码传一个`ApolloConfig`的结构体？

**Comment by zouyx** [comment]
@wangkirin 可以，如有需要我可以进行改造一下，我能请问下，华为也有用吗？ :smile:

**Comment by zouyx** [comment]
@wangkirin 好的，我先调整一个版本，可能要你手工下载一下试试，可以吗？

**Comment by zouyx** [comment]
@wangkirin 下这个tag试试

https://github.com/zouyx/agollo/releases/tag/v1.4.0

例子如下：

``` golang
readyConfig:=&AppConfig{
		AppId:"test1",
		Cluster:"dev1",
		NamespaceName:"application1",
		Ip:"localhost:8889",
	}

	InitCustomConfig(func() (*AppConfig, error) {
		return readyConfig,nil
	})
```

**Comment by wangkirin** [comment]
十分感谢~~~我试一下~~~

**Comment by zouyx** [comment]
在start方法之前调用

**Comment by wangkirin** [comment]
It works，十分感谢~~~

**Comment by zouyx** [comment]
@wangkirin 不用客气，最重要是你能用的爽，如果有问题随时提issue
