### ISSUE TITLE
GetStringValue -  get config value fail!err:Entry not found

### ISSUE THREAD

**Issue by JimChung0403** [zouyx/agollo#23]
請問如果要取得即時數據建議怎麼使用呢？
   透過下面程式, 2分鐘後就會取不到資料
   原因是因為GetStringValue是從cache拿資料
   但是cahce只保存120s, 所以之後都是拿預設值
   所以是否有建議的使用方法呢

   agollo.Start()
    for {
        n := agollo.GetStringValue("name", "default_name")
        fmt.Println(n)
        time.Sleep(5 * time.Second)
    }

**Comment by zouyx** [comment]
@JimChung0403 你是否能使用日志插件，将日志等级跳到debug，将日志截取给我看看？

**Comment by JimChung0403** [comment]
1527471278295579252 [Info] Config Not Modified:<nil>
1527471280299845123 [Debug] allNotifications.getNotifies():[{"namespaceName":"application","notificationId":33}]
Name_is_jim
Name_is_jim
Name_is_jim
Name_is_jim
Name_is_jim
Name_is_jim
1527471310977228799 [Info] Config Not Modified:<nil>
Name_is_jim
1527471312982495293 [Debug] allNotifications.getNotifies():[{"namespaceName":"application","notificationId":33}]
Name_is_jim
Name_is_jim
Name_is_jim
Name_is_jim
default_name
1527471336284111954 [Error] get config value fail!err:Entry not found
default_name
1527471341285830821 [Error] get config value fail!err:Entry not found
1527471343037595750 [Info] Config Not Modified:<nil>
1527471345037990349 [Debug] allNotifications.getNotifies():[{"namespaceName":"application","notificationId":33}]
default_name
1527471346286300054 [Error] get config value fail!err:Entry not found

**Comment by zouyx** [comment]
@JimChung0403 好的，我大概知道问题在哪，晚点检查一下。

**Comment by zouyx** [comment]
@JimChung0403 请问目前你使用的Apollo版本是什么，其他组件的版本也提供一下，谢谢

**Comment by JimChung0403** [comment]
@zouyx ,
我是使用 nobodyiam/apollo-quick-start 這個docker image

**Comment by zouyx** [comment]
@JimChung0403 明白
