### ISSUE TITLE
changeEvent.ChangeType 定義為何

### ISSUE THREAD

**Issue by JimChung0403** [zouyx/agollo#24]
作者你好, 我使用下列方式 取得更換事件

event := agollo.ListenChangeEvent()
changeEvent := <-event

有時後我更該一個存在的key時, ChangeType有時取得1, 有時取得0

似乎長時間不操作後, 就會取得0
之後短時間內有一更新value, 就會取得1

**Comment by zouyx** [comment]
@JimChung0403 该方法为监听值变更的阻塞方法用于自定义值变更后操作。

取得的changeEvent应该是个结构体如下：

···
//config change event
type ChangeEvent struct {
	Namespace string
	Changes map[string]*ConfigChange
}
···

请问问题中提到的0和1，是获取什么值的时候出现呢？如果是获取changeEvent应该不会出现0和1。

**Comment by JimChung0403** [comment]
@zouyx 抱歉, 是我沒說清楚
changeEvent.Changes["nameSpace"].ChangeType

type ConfigChange struct {
	OldValue string
	NewValue string
	ChangeType ConfigChangeType
}

**Comment by zouyx** [comment]
@JimChung0403 关于ConfigChangeType定义如下

0=ADDED是代表该值是新增的
1=MODIFIED是代表该值是被修改过的

···
const(
ADDED ConfigChangeType=iota
MODIFIED
DELETED
)
···

你的意思是ChangeType=0的状态是不正确的？

**Comment by JimChung0403** [comment]
@zouyx 
我有時候 修改apollo上面的value (key為舊的)
但 ConfigChangeType 取得是0

不常發生, 但大多發生在一段時間沒使用的“第一次”
第二次以後 都會取得1

**Comment by zouyx** [comment]
@JimChung0403 我想我知道是什么原因，估计是和#23 一样

**Comment by zouyx** [comment]
@JimChung0403 这个问题你也验证一下。

**Comment by JimChung0403** [comment]
@zouyx 驗證沒問題了, 謝謝

**Comment by zouyx** [comment]
好的，我关闭一下，谢谢你的反馈。
