### ISSUE TITLE
如何获取到全部配置项？

### ISSUE THREAD

**Issue by lemss** [zouyx/agollo#25]
如题，项目需求，需要在APP启动的时候获取到全部的配置项和值，进行定制操作，但是用GetStringValue()只能获取到指定key项的value，在不知道所有key的情况下有方法能一次拿到吗？

另外，同样也遇到了这个bug：https://github.com/zouyx/agollo/issues/23 ，希望能尽快解决，感谢！

**Comment by zouyx** [comment]
@lemss 暂时没有方法获取全部值，你可以参考 [方法](https://github.com/zouyx/agollo/blob/6e914bf1199dd24b1f1cdae155c4f1e810116a5b/repository.go#L107)
重新包装方法出来使用。

另外关于 #23 ，请问目前你使用的Apollo版本是什么？我以前使用那个是没有这种问题的。

**Comment by zouyx** [comment]
其他组件的版本也提供一下

**Comment by lemss** [comment]
刚开始用，直接go get的包，应该都是最新的
golang版本是1.10.2

**Comment by lemss** [comment]
确认了一下，agollo的版本是1.4，使用下面的命令安装的，应该都是最新版：

go get -u github.com/cihub/seelog
go get -u github.com/coocood/freecache
go get -u github.com/zouyx/agollo

**Comment by zouyx** [comment]
@lemss 不好意思，可能你没看太清。。。我说的是**Apollo** 的版本，不是agollo :smiley_cat:

**Comment by lemss** [comment]
@zouyx 抱歉，没看清楚，Apollo用的也是最新版，0.10.2

**Comment by zouyx** [comment]
@lemss 明白，我先尝试重现一下问题。

**Comment by zouyx** [comment]
@lemss #23 已修复，你重新更新一下包试试

**Comment by lemss** [comment]
感谢，我这里验证也没问题了，我把问题关掉

**Comment by lemss** [comment]
辛苦 @zouyx

**Comment by zouyx** [comment]
@lemss 有问题及时反馈。
