### ISSUE TITLE
data race in `currentConnApolloConfig`

### ISSUE THREAD

**Issue by jiajunhuang** [zouyx/agollo#26]
https://github.com/zouyx/agollo/blob/master/repository.go#L42-L44 execute:

`currentConnApolloConfig=&apolloConfig.ApolloConnConfig`

but lock in

```go
type ApolloConnConfig struct {
	AppId string `json:"appId"`
	Cluster string `json:"cluster"`
	NamespaceName string `json:"namespaceName"`
	ReleaseKey string `json:"releaseKey"`
	sync.RWMutex
}
```

will not protect `currentConnApolloConfig` itself, only properties in `currentConnApolloConfig` will be protect.

**Comment by zouyx** [comment]
@jiajunhuang  thanks for your advise. it will be fixed as soon as prosible
