### ISSUE TITLE
配置怎么不落地到文件？放在内存重启重启，配置中新有问题，就坑了

### ISSUE THREAD

**Issue by cafra** [zouyx/agollo#29]

**Comment by zouyx** [comment]
@cafra 你好，很感谢你反馈。目前我记得好像是没有落地写文件。
应该是依赖meta server端的负载均衡，是有客户端容灾。

请问目前遇到什么问题或者问题的场景能不能描述一下呢？

**Comment by cafra** [comment]
客户端的缓存在内存，配置中心出问题的化，应用重启，就丢失了。用另外一个sdk。使用gob 落地就可以客户端容灾了。

**Comment by zouyx** [comment]
@cafra 是的，会出现这种问题。
近期我增加一下写文件的功能。
