### ISSUE TITLE
can not find apollo config!please confirm!

### ISSUE THREAD

**Issue by shaodahong** [zouyx/agollo#30]
```go
agollo.InitCustomConfig(func () (*agollo.AppConfig, error) {
	return &agollo.AppConfig{
		AppId:         "123",
		Cluster:       "456",
		Ip:            "ip",
		NamespaceName: "application",
	}, nil
)
agollo.Start()

**Comment by zouyx** [comment]
你好，是否有在项目目录下增加app.properties的配置文件，具体配置文件可以参考：
https://github.com/zouyx/agollo/blob/master/app.properties

整体项目搭建可以参考：https://github.com/zouyx/agollo_demo

**Comment by shaodahong** [comment]
`app.properties`在其他目录，不在项目目录里，我退到上个版本了，正常使用

**Comment by Gupern** [comment]
> `app.properties`在其他目录，不在项目目录里，我退到上个版本了，正常使用

为什么上个版本就能正常使用？

@zouyx 请问能指定目录读取配置信息吗？或者像上个版本一样运行时指定配置？

**Comment by Gupern** [comment]
试了下，运行多次，有些成功有些不成功，可能是代码repository.go的updateApolloConfig函数里使用了异步：`go writeConfigFile`，

**Comment by zouyx** [comment]
@Gupern 能否提供一下log？

**Comment by iammeizu** [comment]
遇到了相同的问题，已在项目里添加配置信息

**Comment by zouyx** [comment]
好的，我抽空看看，最近比较忙。

**Comment by lilonghe** [comment]
我 fork 之后把 app_config.go 第 225 行注释掉了...
测试了下貌似没有大问题

**Comment by zouyx** [comment]
https://github.com/zouyx/agollo/blob/1c7741dd85847d375ba4f724f584e470900dc8ee/app_config.go#L225

225是这一行？能提一个pr我看看吗？不好意思，最近在有空- -让大家久等了

**Comment by lilonghe** [comment]
@zouyx  这个这个 因为不知道会不会有风险，所以还是你看下改了吧... 我就不提 pr 了
```
func syncServerIpList(newAppConfig *AppConfig) error{
	appConfig:=GetAppConfig(newAppConfig)
	if appConfig==nil{
		return nil
		// panic("can not find apollo config!please confirm!") <- 这个换成了 return nil 
	}
```

**Comment by zouyx** [comment]
@lilonghe ok，我试试看

**Comment by EDDYCJY** [comment]
@zouyx 请问最近有打算修复吗？正打算接入...

**Comment by zouyx** [comment]
@EDDYCJY 这周内解决

**Comment by zouyx** [comment]
@lilonghe @EDDYCJY 你们可以试试master或者v1.6.4，如有问题可以继续反馈或者提pr
