### ISSUE TITLE
配置文件的ip字段如果连接的是nginx配置的转发域名，则在刚启动的时候获取配置成功，之后的心跳检测配置更新出现错误

### ISSUE THREAD

**Issue by Gupern** [zouyx/agollo#35]
心跳检测时报错：
[ERROR] [02:56:57] [requestRecovery @ request.go.104] Connect Apollo Server Fail,Error:<nil>
[ERROR] [02:56:57] [requestRecovery @ request.go.104] Connect Apollo Server Fail,StatusCode:504

是不是apollo.start()的时候，和后面心跳检测的时候，连接方式不一样？

**Comment by zouyx** [comment]
你要看看那个转发的配置是否有加上：
* /configs
* /notifications/v2
* /services/config

应该都是在configserver上

agollo参考：[从该行开始往下](https://github.com/zouyx/agollo/blob/master/app_config.go#L251)

apollo参考：[apollo其他客户端接入](https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97)

**Comment by Gupern** [comment]
![image](https://user-images.githubusercontent.com/10629903/50813118-4bb56000-1350-11e9-9ea4-a36427de0b10.png)

客户端agollo里有ip这个地址，而apollo官方文档写的是如果只指定config_server_url而不指定ip的话，?号后面就不能出现ip。

**Comment by zouyx** [comment]
你指定的只是config_server_url，ip是client端获取到本机ip拼接上去的

**Comment by shanyuyan** [comment]
请问最后有解决这个问题嘛？nginx是怎么配的呢？

**Comment by zouyx** [comment]
@shanyuyan 你遇到的问题是?

**Comment by shanyuyan** [comment]
> @shanyuyan 你遇到的问题是?

是我自己nginx没有配置好，后来解决啦，多谢！

**Comment by zouyx** [comment]
@shanyuyan 好的,不用谢.
