### ISSUE TITLE
指定配置文件启动

### ISSUE THREAD

**Issue by 7-Altman** [zouyx/agollo#37]
指定配置文件去启动Apollo 是得自己重新定义一下，还是说有提供了 类似的方法吗@zouyx

**Comment by zouyx** [comment]
指定配置文件目前好像没有提供方法 - -。。

**Comment by 7-Altman** [comment]
我看了下您是直接写死的。。。改动成本好像有点大。。。

**Comment by 7-Altman** [comment]
> 指定配置文件目前好像没有提供方法 - -。。

我看了下您是直接写死的。。。改动成本好像有点大。。。

**Comment by lilonghe** [comment]
不指定配置文件的话 您那单元测试是怎么跑的呢...

**Comment by 7-Altman** [comment]
> 不指定配置文件的话 您那单元测试是怎么跑的呢...

这个客户端是直接默认了配置文件

**Comment by JungleYe** [comment]
不能指定配置文件的位置，跑test真的是比较麻烦。
