### ISSUE TITLE
show `get config value fail` key name

### ISSUE THREAD

**Issue by lilonghe** [zouyx/agollo#38]
`ERROR apollo: get config value fail!err:Entry not found`
提个建议，如果某个字段不存在，可以把不存在的字段 key name 抛出来。
因为某些原因，会有一些字段特定情况下不会配置，然后出来好几个红色的获取字段失败，但失败的又不知道是哪些，就会比较尴尬。

**Comment by zouyx** [comment]
@lilonghe ok，这周内可以？
