### ISSUE TITLE
不支持yml文件的获取么，是只能获取key-value的配置么

### ISSUE THREAD

**Issue by AdamHyl** [zouyx/agollo#41]
我想使用yml文件作为配置 ，apollo中也添加好了，但是agollo好像是不支持是么？

**Comment by zouyx** [comment]
你的意思是想使用yml配置启动agollo，还是使用agollo读取apollo之中的yml配置项？

**Comment by AdamHyl** [comment]
> 你的意思是想使用yml配置启动agollo，还是使用agollo读取apollo之中的yml配置项？
> 
> 如果是前者，目前好像不支持，后者需要自己弄一下 ：>

想要的是后者，那我看看怎么弄了。谢谢
