### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xkfen** [zouyx/agollo#42]
在app_config.go中，##syncServerIpListSuccessCallBack的参数responseBody，使用string(responseBody)打印出来是标准的html，即apollo的登录页面。
请问如何反序列化为serverInfo？

**Comment by xkfen** [comment]
抱歉了，知道原因在哪里了，我的app.properties里面的ip对应的port没有正确，不应该是8070，应该是8080

**Comment by zouyx** [comment]
好的
