### ISSUE TITLE
[BUG]每个20min刷新ip列表存在对map的并发读写，可能导致panic

### ISSUE THREAD

**Issue by xmac1** [zouyx/agollo#44]
**定时刷新列表存在map并发读写，可能导致panic**

**代码**
```
// 这是写map的函数
func syncServerIpListSuccessCallBack(responseBody []byte) (o interface{}, err error) {
	logger.Debug("get all server info:", string(responseBody))

	tmpServerInfo := make([]*serverInfo, 0)

	err = json.Unmarshal(responseBody, &tmpServerInfo)

	if err != nil {
		logger.Error("Unmarshal json Fail,Error:", err)
		return
	}

	if len(tmpServerInfo) == 0 {
		logger.Info("get no real server!")
		return
	}

	for _, server := range tmpServerInfo {
		if server == nil {
			continue
		}
		servers[server.HomepageUrl] = server
	}
	return
}
```
// 这是读map的函数
func (this *AppConfig) selectHost() string {
	if !this.isConnectDirectly() {
		return this.getHost()
	}

	for host, server := range servers {
		// if some node has down then select next node
		if server.IsDown {
			continue
		}
		return host
	}

	return ""
}

``

**建议**
使用sync.Map

**Comment by zouyx** [comment]
sync.Map是1.9之后的，如果加上估计之前的版本会有兼容性问题。是可以考虑加读写锁。

**Comment by xujianhai666** [comment]
@zouyx 可以发个版本, 低版本 只需要 bugfix，高版本 使用 sync.Map 就可以.

**Comment by zouyx** [comment]
@xmac1 @xujianhai666 如有空请帮忙review，谢谢
