### ISSUE TITLE
[BUG] 当value大到超过cache限制会导致get失败

### ISSUE THREAD

**Issue by matianjun1** [zouyx/agollo#47]
**Describe the bug**
我设置的value大约270kb，超过了freecache包50mb/1024的大小，从repository.go的第90行`apolloConfigCache.Set([]byte(key), []byte(value), expireTime)`可以看出，没有对返回的err进行处理，实际上在set过程中就提示value过大。后期get的时候就提示Entry not found。

**To Reproduce**
1. 使用超过50kb的value
2. 获取该key的结果便会失败

**Comment by zouyx** [comment]
@matianjun1 你好，可以参考一下这个issue，https://github.com/coocood/freecache/issues/28，我稍后可以抽象一个数据存储层，让你自己实现，你看这样可以不？

**Comment by matianjun1** [comment]
我可能考虑直接用sync.Map吧

**Comment by zouyx** [comment]
没问题，哈哈

**Comment by zouyx** [comment]
没问题，但是，我好像是用了freecache的过期特性，我估计你要自己实现过期- -
