### ISSUE TITLE
[BUG] 在 apollo 平台上自定义了环境，代码中 apollo 配置项中没有环境参数字段

### ISSUE THREAD

**Issue by SmileEye** [zouyx/agollo#49]
**Describe the bug**

您好，按照 Apollo 指导添加了新的环境：

https://github.com/ctripcorp/apollo/wiki/%E9%83%A8%E7%BD%B2&%E5%BC%80%E5%8F%91%E9%81%87%E5%88%B0%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#42-%E6%B7%BB%E5%8A%A0%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84%E7%8E%AF%E5%A2%83

代码中 apollo 结构体如下，没有指定环境参数：
```shell
type AppConfig struct {
	AppId string `json:"appId"`
	Cluster string `json:"cluster"`
	NamespaceName string `json:"namespaceName"`
	Ip string `json:"ip"`
	NextTryConnTime int64 `json:"-"`
}
```
想问下您，是不是默认读取的是 DEV 环境，如果添加了新的自定义环境，应该怎么读取。

**Expected behavior**
能够读取自定义环境的参数信息。

**Comment by zouyx** [comment]
ok，如有问题我这周末修复一下

**Comment by betterfor** [comment]
环境通过Ip获取，具体：https://github.com/ctripcorp/apollo/issues/712

**Comment by SmileEye** [comment]
> 环境通过Ip获取，具体：[ctripcorp/apollo#712](https://github.com/ctripcorp/apollo/issues/712)

好的，谢谢啦！
