### ISSUE TITLE
[FEATURE] 支持只提供 namespace 创建 Config 对象

### ISSUE THREAD

**Issue by xujianhai666** [zouyx/agollo#53]
**Is your feature request related to a problem? Please describe.**
java 支 持只提供 namespace 创建 Config 对象 的方式
```
ConfigService.getConfig(url.getParameter(Constants.CONFIG_NAMESPACE_KEY, DEFAULT_GROUP));
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zouyx** [comment]
Ref #18

**Comment by zouyx** [comment]
Ref #18
