### ISSUE TITLE
定时刷新配置出错

### ISSUE THREAD

**Issue by loser54255** [zouyx/agollo#62]
我配置的 namespaceName 不是application，但是刷新的时候取得是默认的application的配置，导致指针错误，希望修复这个bug，可以获取我配置的那个，具体错误位置：zouyx/agollo/repository.go:253

**Comment by zouyx** [comment]
@loser54255 非常感谢你的issue，我明天安排事件尽快修复下。

**Comment by loser54255** [comment]
我认为这个地方应该是刷新所有的配置，麻烦尽快修复一下，正好可以借用

**Comment by zouyx** [comment]
先别急着关闭，还没修复呢大兄弟

**Comment by loser54255** [comment]
手残点错了

**Comment by zouyx** [comment]
@loser54255 v2.1.2试试

**Comment by loser54255** [comment]
感谢，请教个问题，我在go module模式下，使用go get -u github.com/zouyx/agollo 得不到最新的包，使用  go get -u github.com/zouyx/agollo@v2.1.2  指定版本，找不到这个版本

**Comment by loser54255** [comment]
是不是需要您发布到goproxy.io上

**Comment by zouyx** [comment]
[go.mod](https://github.com/zouyx/agollo_demo/blob/master/go.mod)

我是这么用的喔....应该不需要发布到goproxy的.

**Comment by loser54255** [comment]
我把代理关掉了，采用直连的方式，是可以的

**Comment by zouyx** [comment]
@loser54255 ,你试试ali这个代理，https://mirrors.aliyun.com/goproxy/
