### ISSUE TITLE
[FEATURE]测试问题

### ISSUE THREAD

**Issue by zouyx** [zouyx/agollo#65]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by loser54255** [comment]
@zouyx  我也遇到了测试问题，只要项目引入了agollo包，我在任何地方建立 go test文件，启动的时候，都会触发agollo.init()方法，会导致空指针的问题

**Comment by zouyx** [comment]
这个问题可能就有点尴尬............我得想下咋搞.

**Comment by zouyx** [comment]
@loser54255 我试了下应该
