### ISSUE TITLE
[FEATURE]可以支持Apollo的json方式吗

### ISSUE THREAD

**Issue by loser54255** [zouyx/agollo#66]
我定义了一个namespace的配置方式为json，这个有方法可以用吗
需要两个：初始拉取json配置，json配置更新，自动更新

**Comment by zouyx** [comment]
@loser54255 目前不行,有计划支持json和yml

**Comment by zouyx** [comment]
@loser54255 如果你急的话,可以通过listener的方式做

**Comment by loser54255** [comment]
您能说明白一些吗，是需要我自己写监控是吗

**Comment by zouyx** [comment]
是的,用那个listener去更改你的实体

**Comment by loser54255** [comment]
tks，搞定了，想问一下app.properties是否支持环境变量，任何一个都可(最好第一个)
1 根据环境变量加载不同的 .properties
2 app.properties里可以自动识别环境变量

**Comment by zouyx** [comment]
@loser54255 支持是支持,要在namespace那里配置成namespace.json才行,现在我没做类型匹配,所以会获取失败.....我看看怎么改下

**Comment by loser54255** [comment]
可以用的，只不过获取的key是content，就可以获取全部json配置，然后处理的

**Comment by zouyx** [comment]
@loser54255 好，2 app.properties里可以自动识别环境变量，这个具体应用场景是否能简要描述下

**Comment by loser54255** [comment]
配置文件还是 app.properties 这个文件，但是配置文件里，可以按照某种约定，比如 $ENV ,就可以自动把 $ENV 替换成 环境变量env

**Comment by zouyx** [comment]
@loser54255 我知道需求是怎样，我想知道应用场景，就是例如：是在docker环境上吗？

**Comment by loser54255** [comment]
是的，测试和开发环境有很多，如果按照方案一的话，需要建很多配置文件，方案二更合理

**Comment by zouyx** [comment]
@loser54255 现在可以支持各种文件格式化。

**Comment by loser54255** [comment]
tks，我去试试
