### ISSUE TITLE
数据更新增量更新

### ISSUE THREAD

**Issue by ansinlee** [zouyx/agollo#7]
func updateApolloConfigCache(configurations map[string]string,expireTime int)  {
	if configurations==nil||len(configurations)==0{
		return
	}

	apolloConfigCache.Clear()

	for key,value:=range configurations{
		apolloConfigCache.Set([]byte(key),[]byte(value),expireTime)
	}
}

数据更新，先清除apolloConfigCache.Clear()， 再全量写入，写入过程中如果有访问，出现部分key访问不到， 可改成增量更新

func updateApolloConfigCache(configurations map[string]string, expireTime int) {
	if configurations == nil || len(configurations) == 0 {
		return
	}

	updateCacheLock.Lock()
	defer updateCacheLock.Unlock()

	// get old keys 保存老的key
	mp := map[string]bool{}
	it := apolloConfigCache.NewIterator()
	for en := it.Next(); en != nil; en = it.Next() {
		mp[string(en.Key)] = true
	}
	// update new keys  全量更新数据
	for key, value := range configurations {
		apolloConfigCache.Set([]byte(key), []byte(value), expireTime)
		delete(mp, string(key))  // 删已有的key, mp剩下是就要删除的
	}
	// remove del keys 删除新配置中没有的项
	for key := range mp {
		apolloConfigCache.Del([]byte(key))
	}
}
为了防止两次更新同时进行，数据出现问题，在一次数据更新过程中加个锁，保证同时只进行一次数据更新
	updateCacheLock.Lock()
	defer updateCacheLock.Unlock()

**Comment by zouyx** [comment]
可以   :smile:

**Comment by zouyx** [comment]
谢谢提醒！我查了一下，更新入口只有两个，需要增量更新只有这一个，所以没有使用全局锁，本来freecache中已有提供局部锁 😄
