### ISSUE TITLE
[FEATURE]支持多环境

### ISSUE THREAD

**Issue by qiluge** [zouyx/agollo#70]
**Is your feature request related to a problem? Please describe.**

希望能支持一下多环境配置，目前只看到有支持多集群。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zouyx** [comment]
@qiluge 你好，是否能跟我描述一下场景呢

**Comment by qiluge** [comment]
https://github.com/ctripcorp/apollo/wiki/Apollo%E9%85%8D%E7%BD%AE%E4%B8%AD%E5%BF%83%E4%BB%8B%E7%BB%8D#41-core-concepts，https://github.com/ctripcorp/apollo/wiki/Java%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#1241-environment

环境有开发，测试，仿真，生产等环境，集群可以按照数据中心分。

目前的代码里集群是通过app.properties配置的，但是这个配置还不支持Environment配置。

**Comment by qiluge** [comment]
哦，能通过配置不同的IP来对应不同的环境。

**Comment by zouyx** [comment]
@qiluge 你好，我知道了，go这边的实现和java有点不一样

java是通过spring读取各个环境的配置文件，进行分配多环境。

golang是通过各个环境使用不一样的配置文件内容。

当然，你可以使用默认的配置文件，也可以指定配置文件，详情：[点我](https://github.com/zouyx/agollo/wiki/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97#1212%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E6%8C%87%E5%AE%9A%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)

例如：

开发使用application.properties
```
{
    "appId": "test",
    "cluster": "dev",
    "namespaceName": "application.json,a.yml",
    "ip": "localhost:8888"
}
```

测试使用application.properties
```
{
    "appId": "test",
    "cluster": "test",
    "namespaceName": "application.json,a.yml",
    "ip": "localhost:8888"
}
```
