### ISSUE TITLE
[配置中心连不上时，不能容灾]

### ISSUE THREAD

**Issue by zhenyuxie** [zouyx/agollo#75]
**请简单描述bug的场景**
我故意将配置中心地址配错，验证容灾能力，结果再存在本地配置文件的情况下报如下错误：
[loadConfigFile fail,error: [open : no such file or directory]]

**如何重现**
很简单，将配置中心地址填错就行，然后调用 demo 的接口：curl  localhost:9000/check，返回的内容是空的

***bug 位置**
file.go 的 getConfigFile 函数，fullPath 为空时，内部应该返回 filePath

**Comment by zouyx** [comment]
@zhenyuxie 你好，十分感谢你的反馈，我测试了一下
场景应该是在第一次链接服务器失败，因为改实现是长轮询，第二次链接成功是能写这个文件的。

稍后我会修复下这个错误，你可以关注下。
