### ISSUE TITLE
[BUG]invalid module: github.com/zouyx/agollo should be v0 or v1, not v2 (v2.2.1)

### ISSUE THREAD

**Issue by qiluge** [zouyx/agollo#78]
**请简单描述bug的场景**

go mod 引用时，版本号与module的path不匹配，导致无法引用v2.x.x的任何版本。

参考：https://github.com/golang/go/wiki/Modules#semantic-import-versioning，

**Comment by zouyx** [comment]
@qiluge 可以使用的,就是不显示正常的版本号, 会变成这个[go.mod](https://github.com/zouyx/agollo_demo/blob/495032acf229e9dd329484b6a2ad8a96c557cd6b/go.mod#L3)一样

或者你提供一下你的golang版本和执行的命令给我试试?

**Comment by qiluge** [comment]
我直接引用 ```github.com/zouyx/agollo v0.0.0-20191114083447-dde9fc9f35b8```之后，再使用 go mod tidy，go.mod里面会被直接修改为v1.9.0。然后我现在是这么用的
```
require github.com/zouyx/agollo v1.9.0

replace github.com/zouyx/agollo v1.9.0 => github.com/zouyx/agollo v0.0.0-20191114083447-dde9fc9f35b8
```

我的go version：```go version go1.12.7 linux/amd64```

**Comment by zouyx** [comment]
我是输入了v2.2.1
```golang
require github.com/zouyx/agollo v2.2.1
```

使用go mod tidy，就变成了

```golang
require github.com/zouyx/agollo v0.0.0-20191114083447-dde9fc9f35b8
```

**Comment by zouyx** [comment]
@qiluge 你用下面这个应该是可以的.
```golang
require github.com/zouyx/agollo v2.2.1+incompatible
```

**Comment by qiluge** [comment]
好了，多谢！

**Comment by zouyx** [comment]
使用goproxy不能下载， #84
