### ISSUE TITLE
数据长轮询更新

### ISSUE THREAD

**Issue by ansinlee** [zouyx/agollo#8]
func (this *NotifyConfigComponent) Start()  {
	t2 := time.NewTimer(long_poll_interval)
	//long poll for sync
	for {
		select {
		case <-t2.C:
			notifySyncConfigServices()
			t2.Reset(long_poll_interval)
		}
	}
}
notifySyncConfigServices() 中进行请求时，http请求是阻塞住，下在那个timer应该去掉

**Comment by zouyx** [comment]
@ansinlee 
我想了解一下，你的考虑具体场景是什么？

其实，notifySyncConfigServices()在获取完通知更新之后，才会运行t2.Reset(long_poll_interval)。
其实long_poll_interval的时间不要太长就没有问题。
目前已调整至2s，我记得java client是5s。

我主要是在多次连续更新的时候，long_poll_interval这个时间才会真正影响更新速度，不过我觉得这种场景不多。：>
