### ISSUE TITLE
[BUG]获取不到配置信息

### ISSUE THREAD

**Issue by JungleYe** [zouyx/agollo#81]
**请简单描述bug的场景**
执行agollo.Start()之后，立刻执行agollo.GetStringValue()去获取某一个业务配置。此时取到的数值为空

**另外一种尝试**
在执行了agollo.Start()之后，执行Sleep一秒，然后再通过agollo.GetStringValue()获取业务配置时就是正常的。

**Agollo 版本 :**
 - Version [V2.2.2] 今天down下来的最新的代码

**猜测**
不确定是不是跟Start方法中的的几个方法以goroutine的方式启动有关。 我也再验证一下。

**Comment by zouyx** [comment]
有可能是，我今日也试了是有这种问题。

**Comment by zouyx** [comment]
你切回去2.2.1，用这个版本。v2.2.1+incompatible
