### ISSUE TITLE
[FEATURE]增加控制缓存配置的开关

### ISSUE THREAD

**Issue by qiluge** [zouyx/agollo#82]
**功能适用的场景？**
该功能适用于无需缓存文件的场景

**你需要的功能是否有关联问题？**
目前agollo会将配置文件缓存成json文件，落到硬盘上，而且是明文存储，有数据泄露风险。
代码见：https://github.com/zouyx/agollo/blob/master/componet_notify.go#L213

**你期望的解决方案是？**
希望能提供一个开关，控制是否将配置存到本地文件。

**Comment by zouyx** [comment]
可以，可以如果你有实现好的也可以提一下pr
