### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by iammeizu** [zouyx/agollo#83]
**请简单描述bug的场景**

go  module 引用2.0+版本错误

**日志信息**

Not Found: github.com/zouyx/agollo@v2.2.2: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

**解决方案**

做好语义版本控制
go.mod 文件第一行声明改成 module github.com/zouyx/agollo/v2

**建议**

希望能在readme中说明贡献代码的方法，比如开放提交分支的权限

**Comment by zouyx** [comment]
贡献代码方法我稍后补充一下，目前不建议使用v2.2.2，建议使用v2.2.1

[invalid version解决方法](https://github.com/zouyx/agollo/issues/78)

**Comment by iammeizu** [comment]
这个方法应该没问题，但是只是间接的解决了问题，建议还是遵循语义，这样这个问题就不会产生了

**Comment by zouyx** [comment]
是的，目前已经发了的包是暂时只能这样，是否有时间帮忙修改下提个pr？

**Comment by zouyx** [comment]
[CONTRIBUTING.md](https://github.com/zouyx/agollo/blob/master/CONTRIBUTING.md)
