### ISSUE TITLE
go.mod不能下载agollo的解决方法

### ISSUE THREAD

**Issue by zouyx** [zouyx/agollo#85]
* [不能正确显示agollo版本号的解决方法](https://github.com/zouyx/agollo/issues/78)
* [使用goproxy不能下载的解决思路](https://github.com/zouyx/agollo/issues/84)
* [为什么要增加+incompatible](https://github.com/golang/go/wiki/Modules#semantic-import-versioning)

**Comment by a67793581** [comment]
前面两个链接挂了

**Comment by nobodyiam** [comment]
fixed
