### ISSUE TITLE
默认超时时间不合理

### ISSUE THREAD

**Issue by Adol1111** [zouyx/agollo#9]
根据官方文档 /notifications/v2接口会hold至少30S，官方建议timeout时间至少30S，最好是60S以上，目前默认值是1S，项目启动后会报超时错误

目前的connect_timeout和其他请求是共用的，可以考虑分两个超时时间。

**Comment by zouyx** [comment]
@Adol1111 ，谢谢你的反馈，你的意思是想连接/notifications/v2接口是30s超时，其他接口是默认超时时间是吗？

**Comment by Adol1111** [comment]
是的，目前看官方的文档，只有这个接口是做了特殊说明，其他的用目前的值应该没什么问题

https://github.com/ctripcorp/apollo/wiki/%E5%85%B6%E5%AE%83%E8%AF%AD%E8%A8%80%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97

**Comment by Adol1111** [comment]
刚刚看了一下，官方的java客户端，默认时间好像是10分钟，关于长轮询的超时时间可以参考一下

https://github.com/ctripcorp/apollo/blob/master/apollo-client/src/main/java/com/ctrip/framework/apollo/internals/RemoteConfigLongPollService.java#L165

**Comment by zouyx** [comment]
@Adol1111 好的，谢谢
