### ISSUE TITLE
[BUG] Apollo服务未启动时，调用获取配置会阻塞进程

### ISSUE THREAD

**Issue by youran0715** [zouyx/agollo#92]
Apollo服务关闭，客户端程序重启即可复现。

看代码GetConfigValue 会判断是否初始化 没有初始化则获取 但服务不可用 会阻塞进程

**Comment by zouyx** [comment]
已知问题，现在正在整个lib重构。

**Comment by zouyx** [comment]
fixed in v3.0.0-alpha
