### ISSUE TITLE
[FEATURE] 需要能指定backupConfigFileName

### ISSUE THREAD

**Issue by lj99boy** [zouyx/agollo#94]
**功能适用的场景？**
本地存储远程namespace文件时，指定输出文件名

**你需要的功能是否有关联问题？**
这样可以更灵活支持其他语言使用namespace，如php直接读取配置文件

**你期望的解决方案是？**
file.go的suffix功能得到拓展，对namespace可以自定义输出文件名

**Comment by zouyx** [comment]
@lj99boy 可以，如果你修改了也可以提个PR。

**Comment by lj99boy** [comment]
好的！您等等我这个PR。 @zouyx
